---
- name: check for require directory in to {{ glx_ndjbdns_sysconfdir }}/ndjbdns directory
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  loop:
    - "{{ glx_tinydns_root_directory }}"
    - "{{ glx_tinydns_zones_directory }}"
    - "{{ glx_tinydns_primary_directory }}"
    - "{{ glx_tinydns_secondary_directory }}"

- name: check {{ glx_ndjbdns_prefix }}/bin/refreshzones
  template:
    src: refreshzones.sh
    dest: "{{ glx_ndjbdns_prefix }}/bin/refreshzones"
    mode: 0755
    backup: no

- name: check {{ glx_ndjbdns_sysconfdir }}/ndjbdns/Makefile
  template:
    src: Makefile.j2
    dest: "{{ glx_tinydns_root_directory }}/Makefile"
    backup: no

- name: check /root/.ssh
  file:
    path: "/root/.ssh"
    owner: "root"
    group: "root"
    state: directory
    mode: 0700

- name: check /root/.ssh/{{ item.priv_key_name }}
  copy:
    src: "../keys/{{ item.priv_key_name }}"
    dest: "/root/.ssh/{{ item.priv_key_name }}"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: no
  loop: glx_domain_list
  ignore_errors: true