---
- name: Ensure ntpdate is absent
  apt:
    pkg:
      - ntpdate
    state: absent
    purge: yes

- name: Ensure id ntpd is present
  apt:
    pkg:
      - ntp
      - tzdata
    state: present

- name: ntp time source
  template:
    src: ntp-server.conf.j2
    dest: /etc/ntp.conf
  notify: Restart ntp service

- name: remove dhcp-ntp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/dhcp/dhclient-exit-hooks.d/ntp"
    - "/var/lib/ntp/ntp.conf.dhcp"
  notify: Restart ntp service

- name: Ensure NTP is running and enabled as configured.
  service:
    name: nrp
    state: started
    enabled: true
  when: ntp_enabled | bool

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: ntp
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool)

- meta: flush_handlers