---
- name: Configure openssh client
  template:
    src: "ssh_config.j2"
    dest: "/etc/ssh/ssh_config"
  notify: Restart ssh service

- name: Configure openssh server
  template:
    src: "sshd_config.j2"
    dest: /etc/ssh/sshd_config
    backup: yes
    validate: "/usr/sbin/sshd -T -f %s"
  notify:
    - Restart ssh service

- name: Disable local mail checking after login
  lineinfile:
    dest: /etc/pam.d/sshd
    backrefs: yes
    state: present
    regexp: "^session    optional     pam_mail.so standard noenv"
    line: "#session    optional     pam_mail.so standard noenv \\# [1]"

