---
- name: Check if {{ system_base_primary_local }} locale present
  tags: locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ system_base_primary_local }}"
    - "{{ system_base_secondary_local }}"
  register: locale_gen_status

- name: Update and Set locale
  tags: locales
  command: >-
    /usr/sbin/update-locale LANG={{ system_base_primary_local }} LANGUAGE={{ system_base_language }}
  when:
    - locale_gen_status.changed

- name: Install manpages in desired language
  apt:
    pkg:
      - "manpages-{{ system_base_language }}"
  when: (system_base_enable_manpages | bool)
