# https://angristan.fr/installer-php-7-debian-8-jessie-depot-dotdeb/
- name: php7 | Check php installation
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-mysql
    - php7.0-curl
    - php7.0-json
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-msgpack
    - php7.0-memcached
    - php7.0-intl
    - php7.0-sqlite3
    - php7.0-gmp
    - php7.0-geoip
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
    - mysql-utilities

- name: php7 | check max_execution_time
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; max_execution_time = [0-9]+|^max_execution_time = [0-9]+'
    replace='max_execution_time = 30'
  notify:
    - service apache2 restart

- name: php7 | using max_execution_time = 30
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='max_execution_time = 30'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check max_input_time
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; max_input_time = [0-9]+|^max_input_time = [0-9]+'
    replace='max_input_time = 60'
  notify:
    - service apache2 restart

- name: php7 | using max_input_time = 60
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='max_input_time = 60'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check memory_limit
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; memory_limit = [a-zA-Z0-9_]+|^memory_limit = [a-zA-Z0-9_]+'
    replace='memory_limit = 128M'
  notify:
    - service apache2 restart

- name: php7 | using memory_limit = 128M
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='memory_limit = 128M'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check upload_max_filesize
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; upload_max_filesize = [a-zA-Z0-9_]+|^upload_max_filesize = [a-zA-Z0-9_]+'
    replace='upload_max_filesize = 10M'
  notify:
    - service apache2 restart

- name: php7 | using upload_max_filesize = 10M
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='upload_max_filesize = 10M'
    state=present
  notify:
    - service apache2 restart

# Don't exist anymore
#- name: php7 | check register_globals
#  replace:
#    dest='/etc/php/7.0/apache2/php.ini'
#    regexp='^\; register_globals = [a-zA-Z0-9_]+|^register_globals = [a-zA-Z0-9_]+'
#    replace='register_globals = Off'
#  notify:
#    - service apache2 restart
#
#- name: php7 | using register_globals = Off
#  lineinfile:
#    dest='/etc/php/7.0/apache2/php.ini'
#    line='register_globals = Off'
#    state=present
#  notify:
#    - service apache2 restart

# Disable server Signature and Version thing
# [inspired_by] http://ask.xmodulo.com/turn-off-server-signature-apache-web-server.html
- name: php7 | check expose_php
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; expose_php = [a-zA-Z0-9_]+|^expose_php = [a-zA-Z0-9_]+'
    replace='expose_php = Off'
  notify:
    - service apache2 restart
# Disable server Signature and Version thing
# [inspired_by] http://ask.xmodulo.com/turn-off-server-signature-apache-web-server.html
- name: php7 | using expose_php = Off
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='expose_php = Off'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check mbstring.language
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; mbstring.language =[^\n]*\n+|^mbstring.language =[^\n]*\n|^\;mbstring.language =[^\n]*\n'
    replace='mbstring.language = UTF-8\n'
  notify:
    - service apache2 restart

- name: php7 | using mbstring.language = UTF-8
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='mbstring.language = UTF-8'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check mbstring.internal_encoding
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; mbstring.internal_encoding =[^\n]*\n|^mbstring.internal_encoding =[^\n]*\n|^\;mbstring.internal_encoding =[^\n]*\n'
    replace='mbstring.internal_encoding = UTF-8\n'
  notify:
    - service apache2 restart

- name: php7 | using mbstring.internal_encoding = UTF-8
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='mbstring.internal_encoding = UTF-8'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check mbstring.http_input
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; mbstring.http_input =[^\n]*\n|^mbstring.http_input =[^\n]*\n|^\;mbstring.http_input =[^\n]*\n'
    replace='mbstring.http_input = UTF-8\n'
  notify:
    - service apache2 restart

- name: php7 | using mbstring.http_input = UTF-8
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='mbstring.http_input = UTF-8'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check mbstring.http_output
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; mbstring.http_output =[^\n]*\n|^mbstring.http_output =[^\n]*\n|^\;mbstring.http_output =[^\n]*\n'
    replace='mbstring.http_output = UTF-8\n'
  notify:
    - service apache2 restart

- name: php7 | using mbstring.http_output = UTF-8
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='mbstring.http_output = UTF-8'
    state=present
  notify:
    - service apache2 restart

- name: php7 | check mbstring.detect_order
  replace:
    dest='/etc/php/7.0/apache2/php.ini'
    regexp='^\; mbstring.detect_order =[^\n]*\n|^mbstring.detect_order =[^\n]*\n|^\;mbstring.detect_order =[^\n]*\n'
    replace='mbstring.detect_order = auto\n'
  notify:
    - service apache2 restart

- name: php7 | using mbstring.detect_order = auto
  lineinfile:
    dest='/etc/php/7.0/apache2/php.ini'
    line='mbstring.detect_order = auto'
    state=present
  notify:
    - service apache2 restart