---
galaxy_info:
  author: Bert Van Vreckem
  description: Role for setting up a PXE server on RHEL/CentOS 7
  company:
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - networking
dependencies:
  - bertvv.tftp
  - bertvv.dhcp
