---
# handlers file for peertube

- name: reload systemd
  become: yes
  systemd: daemon_reload=yes
  changed_when: True

- name: reload nginx
  become: yes
  service: name=nginx state=reloaded
  changed_when: True

- name: "reload {{ peertube_service_name }}"
  become: yes
  service: 
    name: "{{ peertube_service_name }}" 
    state: reloaded
  changed_when: True

