---
- name: Restart peertube service
  systemd:
    name: peertube
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload nginx service
  systemd:
    name: nginx
    state: reloaded
    enabled: yes
