---
# Common and path
glx_prefix_dir: "/usr/local"
glx_sysprefix_dir: "/etc"
glx_slashpackage_dir: "/package"

# fehqlibs
glx_nacl_force_install: false
glx_nacl_app_name: "nacl"
glx_nacl_app_version: "20110221"
glx_nacl_archive_extension: "tar.bz2"
glx_nacl_archive_filename: "{{ glx_nacl_app_name }}-{{ glx_nacl_app_version }}.{{ glx_nacl_archive_extension }}"
glx_nacl_download_repository: "https://gitlab.com/Tuuux/galaxie/raw/master/roles/nacl/files"
glx_nacl_download_file: "{{ glx_nacl_download_repository }}/{{ glx_nacl_archive_filename }}"
glx_nacl_download_file_sha1sum: "6007a6aee249f5a534ec53fddfc364601fba9629"
glx_nacl_source_dir: "/usr/src"

