---
- name: Source specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install nginx
  package:
    name: nginx

- name: Create modular configuration directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop: "{{ nginx_modular_config_directories }}"

- name: Configure nginx
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_file }}"
    mode: 0644
    owner: root
    group: root
  notify: Reload nginx service

- name: Ensure nginx is started
  systemd:
    name: nginx
    enabled: yes
    state: started
    daemon_reload: yes
