---
postfix_has_virtual_aliases: "{{ postfix_virtual_aliases | length > 0 }}"
postfix_has_virtual_aliases_domains: "{{ postfix_virtual_aliases_domains | length > 0 }}"
postfix_has_virtual_mailboxes: "{{ postfix_virtual_mailboxes | length > 0 }}"
postfix_has_virtual_mailbox_domains: "{{ postfix_virtual_mailbox_domains | length > 0 }}"
postfix_has_transports: "{{ postfix_transports | length > 0 }}"
