---
#
# General
#
ansible_python_interpreter: /usr/bin/python3
ssl_certs_dir: "/etc/ssl/private"
#
# PLAYBOOK clan-install.yml
#
clan_install_system_packages:
  - apt-transport-https
  - aptitude
  - build-essential
  - git
  - libffi-dev
  - libperl-dev
  - libssl-dev
  - python3
  - python3-apt
  - python3-distutils-extra
  - python3-venv
  - python3-pip
  - python3-setuptools
  - python-apt-dev
  - sudo
clan_caretaker_name: zoe
clan_caretaker_uid: 4200
clan_caretaker_gid: 4200
clan_caretaker_home: "/home/{{ clan_caretaker_name }}"
clan_allies_group: "{{ clan_name }}_allies"
clan_allies_os_group: "allies"
clan_allies_keystore_path: "{{ playbook_dir }}/../keys/{{ clan_name }}/allies"
clan_alliance_export_content: |-
  {{
    clan_allies_export[with_clan]
    | default({})
    | to_nice_yaml
  }}
#
# ROLE: bind
#
bind_user_keys_algorithm: HMAC-SHA512
bind_user_keys_size: 512
bind_user_keys_directory: /etc/bind/keys
#
# ROLE: common
#