---
- name: ucspi-ssl | install packages for ucspi-ssl building
  apt:
    pkg:
      - "build-essential"
      - "libssl-dev"
      - "libperl-dev"
      - "libkrb5-dev"
    state: present


- name: ucspi-ssl | check {{ glx_slashpackage_dir }} directory
  file:
    path: "{{ glx_slashpackage_dir }}"
    state: directory
    mode: 1755

- name: ucspi-ssl | check {{ glx_ucspi_ssl_source_dir }} directory
  file:
    path: "{{ glx_ucspi_ssl_source_dir }}"
    state: directory

- name: ucspi-ssl | delete "{{ glx_ucspi_ssl_archive_path }}"
  file:
    path: "{{ glx_ucspi_ssl_archive_path }}"
    state: absent
  when: glx_ucspi_ssl_force_install

- name: ucspi-ssl | get "{{ glx_ucspi_ssl_download_file }}"
  get_url:
    url: "{{ glx_ucspi_ssl_download_file }}"
    dest: "{{ glx_ucspi_ssl_source_dir }}"
    sha256sum: "{{ glx_ucspi_ssl_download_file_sha256sum }}"
  register: glx_ucspi_ssl_download
#
#- name: ucspi-ssl | delete "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}" directory
#  file:
#    path="{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}"
#    state=absent
#  when: glx_ucspi_ssl_download.changed
#
#- name: ucspi-ssl | unarchive {{ glx_ucspi_ssl_download.dest }}
#  unarchive:
#    src="{{ glx_ucspi_ssl_download.dest }}"
#    dest="{{ glx_slashpackage_dir }}"
#    copy=no
#  when: glx_ucspi_ssl_download.changed
#
#- name: ucspi-ssl | fixe permissions
#  file:
#    path="{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}"
#    owner="root"
#    group="root"
#    recurse=yes
#  when: glx_ucspi_ssl_download.changed
#
## This is the sslserver DH parameter file.
#- name: ucspi-ssl | check "{{ glx_ucspi_ssl_certificates_dir }}" directory
#  file:
#    path="{{ glx_ucspi_ssl_certificates_dir }}"
#    owner="root"
#    group="root"
#    state=directory
#    mode=0755
#
#- name: ucspi-ssl | generate {{ glx_sqmail_openssl_key_bit }} bits dh parameter "{{ glx_ucspi_ssl_dh_parameter_file }}" fle
#  shell: openssl dhparam -out {{ glx_ucspi_ssl_dh_parameter_file }} {{ glx_sqmail_openssl_key_bit }}
#    creates=/etc/ssl/certs/dhparam.pem
#
#- name: ucspi-ssl | check DEB_BUILD_ARCH
#  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
#  when: ansible_os_family == "Debian"
#  register: DEB_BUILD_ARCH
#  changed_when: false
#
## send conf-* files
#- name: ucspi-ssl | check conf-*
#  template:
#    src="ucspi-ssl/src/{{ item }}.j2"
#    dest="{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/{{ item }}"
#  with_items:
#    - "conf-cadir"
#    - "conf-cafile"
#    - "conf-cc"
#    - "conf-ccafile"
#    - "conf-ccperl"
#    - "conf-certchainfile"
#    - "conf-certfile"
#    - "conf-ciphers"
#    - "conf-dhfile"
#    - "conf-dl"
#    - "conf-keyfile"
#    - "conf-ld"
#    - "conf-ldperl"
#    - "conf-perl"
#    - "conf-rsa"
#    - "conf-ssl"
#    - "conf-ssllib"
#    - "conf-tcpbin"
#
## continue by build the programme
#- name: ucspi-ssl | package/compile
#  shell: package/install
#    chdir="{{ glx_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
#  when: glx_ucspi_ssl_download.changed
#
#- name: ucspi-ssl | package/install
#  shell: package/install
#    chdir="{{ glx_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
#  when: glx_ucspi_ssl_download.changed
#
#- name: ucspi-ssl | package/man
#  shell: package/man
#    chdir="{{ glx_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
#  when: glx_ucspi_ssl_download.changed