---
- name: ucspi-ssl | install packages for ucspi-ssl building
  apt:
    pkg:
      - "build-essential"
      - "libssl-dev"
      - "libperl-dev"
      - "libkrb5-dev"
    state: present


- name: ucspi-ssl | check {{ glx_slashpackage_dir }} directory
  file:
    path: "{{ glx_slashpackage_dir }}"
    state: directory
    mode: 1755

- name: ucspi-ssl | check {{ glx_ucspi_ssl_source_dir }} directory
  file:
    path: "{{ glx_ucspi_ssl_source_dir }}"
    state: directory

- name: ucspi-ssl | delete "{{ glx_ucspi_ssl_archive_path }}"
  file:
    path: "{{ glx_ucspi_ssl_archive_path }}"
    state: absent
  when: glx_ucspi_ssl_force_install

- name: ucspi-ssl | get "{{ glx_ucspi_ssl_download_file }}"
  get_url:
    url: "{{ glx_ucspi_ssl_download_file }}"
    dest: "{{ glx_ucspi_ssl_source_dir }}"
    sha256sum: "{{ glx_ucspi_ssl_download_file_sha256sum }}"
  register: glx_ucspi_ssl_download

- name: ucspi-ssl | delete "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}" directory
  file:
    path: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}"
    state: absent
  when: glx_ucspi_ssl_download.changed

- name: ucspi-ssl | unarchive {{ glx_ucspi_ssl_download.dest }}
  unarchive:
    src: "{{ glx_ucspi_ssl_download.dest }}"
    dest: "{{ glx_slashpackage_dir }}"
    copy: no
  when: glx_ucspi_ssl_download.changed

- name: ucspi-ssl | fixe "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}" permissions
  file:
    path: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}"
    owner: "root"
    group: "root"
    recurse: yes
  when: glx_ucspi_ssl_download.changed

## This is the sslserver DH parameter file.
#- name: ucspi-ssl | check "{{ glx_ucspi_ssl_certificates_dir }}" directory
#  file:
#    path="{{ glx_ucspi_ssl_certificates_dir }}"
#    owner="root"
#    group="root"
#    state=directory
#    mode=0755cat
#
#- name: ucspi-ssl | generate {{ glx_sqmail_openssl_key_bit }} bits dh parameter "{{ glx_ucspi_ssl_dh_parameter_file }}" fle
#  shell: openssl dhparam -out {{ glx_ucspi_ssl_dh_parameter_file }} {{ glx_sqmail_openssl_key_bit }}
#    creates=/etc/ssl/certs/dhparam.pem
#
#- name: ucspi-ssl | check DEB_BUILD_ARCH
#  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
#  when: ansible_os_family == "Debian"
#  register: DEB_BUILD_ARCH
#  changed_when: false
#
## send conf-* files
- name: ucspi-ssl | check conf-*
  template:
    src: "{{ item }}.j2"
    dest: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}/{{ item }}"
  with_items:
    - "conf-cadir"
    - "conf-cafile"
    - "conf-cc"
    - "conf-ccafile"
    - "conf-ccperl"
    - "conf-certchainfile"
    - "conf-certfile"
    - "conf-ciphers"
    - "conf-dhfile"
    - "conf-home"
    - "conf-keyfile"
    - "conf-ld"
    - "conf-ldperl"
    - "conf-man"
    - "conf-perl"
    - "conf-qlibs"
    - "conf-rsa"
    - "conf-ssl"
    - "conf-ssllib"

# continue by build the programme
- name: ucspi-ssl | package/compile
  shell: package/install
  args:
    chdir: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_app_name }}-{{ glx_ucspi_ssl_app_version }}"
  when: glx_ucspi_ssl_download.changed
