---
- name: Restart matrix service
  systemd:
    name: matrix-synapse
    state: restarted
    enabled: yes

- name: Restart nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart coturn service
  systemd:
    name: coturn
    state: restarted
    enabled: yes

- name: Restart sydent service
  systemd:
    name: matrix-sydent
    state: restarted
    enabled: yes
    daemon_reload: yes
