---
### HTTP
- name: apache2 | creat HTTP virtual hosts files
  template:
    src="virtualhost.j2"
    dest="{{ glx_apache_sysconfdir }}/apache2/sites-available/{{ item.ServerName }}.conf"
    owner="root"
    group="root"
    mode=0644
  with_items: glx_apache_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | creat DocumentRoot dor for each HTTP Virtual hosts
  file:
    path="{{ item.DocumentRoot }}"
    state=directory
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    mode=2775
  with_items: glx_apache_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | blanck page if need
  copy:
    src=index.php
    dest={{ item.DocumentRoot }}/index.php
    force=no
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    mode=0664
  with_items: glx_apache_virtualhosts

# Enable HTTP Virtual Hosts
- name: apache2 | a2ensite virtual hosts
  command: a2ensite {{ item.ServerName }}
    creates="{{ glx_apache_sysconfdir }}/apache2/sites-enabled/{{ item.ServerName }}.conf"
  with_items: glx_apache_virtualhosts
  notify:
    - service apache2 restart

### HTTPS

- name: apache2 | creat HTTPS virtual hosts files
  template:
    src="virtualhost-ssl.j2"
    dest="{{ glx_apache_sysconfdir }}/apache2/sites-available/{{ item.ServerName }}-ssl.conf"
    owner="root"
    group="root"
    mode=0644
  with_items: glx_apache_ssl_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | creat DocumentRoot dor for each HTTPS Virtual hosts
  file:
    path="{{ item.DocumentRoot }}"
    state=directory
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    mode=2775
  with_items: glx_apache_ssl_virtualhosts
  notify:
    - service apache2 restart

- name: apache2 | blanck page if need
  copy:
    src=index.php
    dest={{ item.DocumentRoot }}/index.php
    force=no
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    mode=0664
  with_items: glx_apache_ssl_virtualhosts

# Enable HTTPS Virtual Hosts
- name: apache2 | a2ensite SSL virtual hosts
  command: a2ensite {{ item.ServerName }}-ssl
    creates="{{ glx_apache_sysconfdir }}/apache2/sites-enabled/{{ item.ServerName }}-ssl.conf"
  with_items: glx_apache_ssl_virtualhosts
  notify:
    - service apache2 restart
