---
# [inspired_by] https://wiki.debian.org/WordPress#An_alternate_installation_method
# [inspired_by] /usr/share/doc/wordpress/README.Debian

- name: create wordpress configuration file peer ServerName
  template:
    src="wordpress_configuration_file.j2"
    dest="{{ glx_wordpress_sysconfdir }}/wordpress/config-{{ item.ServerName }}.php"
    owner="root"
    group="{{ glx_apache_gname }}"
    mode=0640
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

- name: creat every wp-content directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#blogs.dir
- name: creat every wp-content/blogs.dir directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/blogs.dir"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#languages
- name: creat every wp-content/languages directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/languages"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#plugins
- name: creat every wp-content/plugins directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/plugins"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#themes
- name: creat every wp-content/themes directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/themes"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#upgrade
- name: creat every wp-content/upgrade directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/upgrade"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

#uploads
- name: creat every wp-content/uploads directory
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/uploads"
    mode="2775"
    owner="{{ glx_apache_uname }}"
    group="{{ glx_apache_gname }}"
    state=directory
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  notify:
    - service apache2 restart

# Suppress blogs.dir link
- name: check if {{ glx_wordpress_root_dir }}/wp-content/blogs.dir is a symlink
  stat:
    path="{{ glx_wordpress_root_dir }}/wp-content/blogs.dir"
  register: blogs_dir

#- debug: msg="{{ blogs_dir }}"

- name: remove {{ glx_wordpress_root_dir }}/wp-content/blogs.dir (only if it is a link)
  file:
    path="{{ glx_wordpress_root_dir }}/wp-content/blogs.dir"
    state=absent
  when: blogs_dir.stat.islnk is defined and blogs_dir.stat.islnk

- name: creat {{ glx_wordpress_root_dir }}/wp-content/blogs.dir
  file:
    path="{{ glx_wordpress_root_dir }}/wp-content/blogs.dir"
    mode="0755"
    owner="root"
    group="root"
    state=directory

# Supress uploads link
- name: check if {{ glx_wordpress_root_dir }}/wp-content/uploads is a symlink
  stat:
    path="{{ glx_wordpress_root_dir }}/wp-content/uploads"
  register: uploads_dir

#- debug: msg="{{ blogs_dir }}"

- name: remove {{ glx_wordpress_root_dir }}/wp-content/uploads (only if it is a link)
  file:
    path="{{ glx_wordpress_root_dir }}/wp-content/uploads"
    state=absent
  when: uploads_dir.stat.islnk is defined and uploads_dir.stat.islnk

- name: creat {{ glx_wordpress_root_dir }}/wp-content/uploads
  file:
    path="{{ glx_wordpress_root_dir }}/wp-content/uploads"
    mode="0755"
    owner="root"
    group="root"
    state=directory

# Final
- name: populate wp-content of each virtualhost
  shell: cp -R {{ glx_wordpress_root_dir }}/wp-content/* {{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/
    chdir="{{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}/"
  with_items: "{{ glx_apache_ssl_virtualhosts }}"

  changed_when: false

## Check permission
- name: wordpress chanche owner of subdir in {{ glx_wordpress_content_dir }}/
  shell: chown -R {{ glx_apache_uname }}:{{ glx_apache_gname }} {{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  changed_when: false

- name: wordpress remove write permission to others of subdir in {{ glx_wordpress_content_dir }}/
  shell: chmod -R o-w {{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  changed_when: false

- name: wordpress set files to 664 and directory to 775
  shell: chmod -R u+rwX,g+rwX,o+rX {{ glx_wordpress_content_dir }}/{{ item.ServerName }}/{{ glx_wordpress_wp_content_dirname }}
  with_items: "{{ glx_apache_ssl_virtualhosts }}"
  changed_when: false

# Clean Up
- name: clean up previous mono-domain directory's
  file:
    path="{{ glx_wordpress_content_dir }}/{{ item }}"
    state=absent
  with_items:
    - "blogs.dir"
    - "languages"
    - "plugins"
    - "themes"
    - "upgrade"
    - "uploads"

- name: enable rewrite for DocumentRootDir / by default
  template:
    src="htaccess.j2"
    dest="{{ glx_wordpress_sysconfdir }}/wordpress/htaccess"
    owner="root"
    group="root"
    mode=0644
  notify:
    - service apache2 restart
