---
- name: sqmail | uninstall qmails debian packages
  apt:
    pkg:
      - "qmail-run"
      - "qmail-tools"
      - "qmail"
      - "qmail-uids-gids"
      - "dot-forward"
      - "exim4-base"
      - "exim4-config"
      - "exim4-daemon-light"
    state: absent

- name: sqmail | install require packages for s/qmail building
  apt:
    pkg:
      - "build-essential"
      - "libssl-dev"
      - "libperl-dev"
    state: present

- name: sqmail | check {{ glx_slashpackage_dir }} directory
  file:
    path: "{{ glx_slashpackage_dir }}"
    state: directory
    mode: 1755

- name: sqmail | check {{ glx_sqmail_source_dir }} directory
  file:
    path: "{{ glx_sqmail_source_dir }}"
    state: directory

- name: sqmail | delete "{{ glx_sqmail_downloaded_file }}"
  file:
    path: "{{ glx_sqmail_downloaded_file }}"
    state: absent
  when: glx_sqmail_force_install

- name: sqmail | get "{{ glx_sqmail_download_file }}"
  get_url:
    url: "{{ glx_sqmail_download_file }}"
    dest: "{{ glx_sqmail_source_dir }}"
    sha256sum: "{{ glx_sqmail_download_file_sha256sum }}"
  register: glx_sqmail_download
#
##- name: sqmail | send sqmail source
##  file:
##    source="{{ glx_sqmail_source_name }}.{{ glx_sqmail_source_extension }}"
#
- name: sqmail | delete "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_source_name }}" directory
  file:
    path: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
    state: absent
  when: glx_sqmail_download.changed

- name: sqmail | unarchive {{ glx_sqmail_download.dest }}
  unarchive:
    src: "{{ glx_sqmail_download.dest }}"
    dest: "{{ glx_slashpackage_dir }}"
    copy: no
  when: glx_sqmail_download.changed

- name: sqmail | fixe permissions
  file:
    path: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
    owner: "root"
    group: "root"
    recurse: yes
  when: glx_sqmail_download.changed

# send conf-* files
- name: sqmail | check conf-*
  template:
    src: "{{ item }}.j2"
    dest: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}/{{ item }}"
  with_items:
    - "conf-break"
    - "conf-cc"
    - "conf-delivery"
    - "conf-djbdns"
    - "conf-groups"
    - "conf-home"
    - "conf-idn2"
    - "conf-ids"
    - "conf-instances"
    - "conf-ld"
    - "conf-log"
    - "conf-man"
    - "conf-patrn"
    - "conf-qmq"
    - "conf-spawn"
    - "conf-split"
    - "conf-svcdir"
    - "conf-ucspissl"
    - "conf-users"

- name: sqmail | check scripts
  template:
    src: "service/{{ item }}.j2"
    dest: "{{ glx_sqmail_service_scripts_dir }}/{{ item }}"
  with_items:
    - "ssl.env"

- name: sqmail | package/dir -- sets up the directories
  shell: package/dir
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/ids -- sets up the s/qmail users
  shell: package/ids
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/ucspissl -- hooks up the required sources and libs with package ucspi-ssl
  shell: package/ucspissl
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/compile -- compiles the sources
  shell: package/compile
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/upgrade -- potentially does the upgrade
  shell: package/upgrade
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/legacy -- installs the binaries in the qmail directory
  shell: package/legacy
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/man -- installes the man pages
  shell: package/man
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

- name: sqmail | package/sslenv -- sets up the SSL/TLS environments together with X.509 certs and key files (from ucspi-ssl)
  shell: package/sslenv
  args:
    chdir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
  when: glx_sqmail_download.changed
  changed_when: false

