galaxy_info:
  author: Aurélien Maury
  description: Simple Nginx with default conf file
  company: wescale.fr

#  issue_tracker_url: https://gitlab.com/wescalefr-oss/ansible-roles/raw_nginx/issues

  license: GPLv3

  min_ansible_version: 2.7

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
