---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - echo "MASTER VERSION"
---
kind: signature
hmac: 73c5a1352255ccd0eeee29930022c4cbb562cb19503d120a9b61a071b180cf01

...
