image: docker:stable
services:
  - docker:stable-dind
stages:
  - build
  - tests

build-debian-10:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:Debian-10" --pull -t "$CI_REGISTRY_IMAGE:Debian-10" -f tests/dockerfiles/Debian/10/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:Debian-10"
  only:
    - master

test-debian-10:
  stage: tests
  image: "$CI_REGISTRY_IMAGE:Debian-10"
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -U pip wheel
    - pip3 install -U -r requirements.txt
    - which python3
