- hosts: localhost
  gather_facts: no
  become: no

  vars:
    record_types:
      - A
      - AAAA
      - CNAME
      - DNAME
      - DLV
      - DNSKEY
      - DS
      - HINFO
      - LOC
      - MX
      - NAPTR
      - NS
      - NSEC3PARAM
      - PTR
      - RP
      - RRSIG
      - SOA
      - SPF
      - SRV
      - SSHFP
      - TLSA
      - TXT
    domain_prefix: "rntp.org/"
    auth_server: "@5.135.153.85"

  tasks:
    - set_fact:
        visible_zone: >-
          {{
            visible_zone|default({})
            |combine(
              { (item): lookup('dig', 'rtnp.org/' + item, '@5.135.153.85', wantlist=True) }
            )
          }}
      loop: "{{ record_types }}"

    - debug:
        var: visible_zone