site_name: Galaxie Clans

nav:
  - 'Home': 'README.md'
  - 'Tutorials': '_TUTO__.md'
  - 'Topics Guides': '_TOPIC__.md'
  - 'How-To Guides': '_HOWTO__.md'
  - 'References Guides': '_REF__.md'
  - 'Users Guides': '_UREF__.md'

theme: material