---
- name: "bertvv.bind"
  src: "git+https://github.com/bertvv/ansible-role-bind.git"
  version: "master"

- name: "bertvv.dhcp"
  src: "git+https://github.com/bertvv/ansible-role-dhcp.git"
  version: "master"

- name: "bertvv.tftp"
  src: "git+https://github.com/bertvv/ansible-role-tftp.git"
  version: "master"

- name: "bertvv.pxeserver"
  src: "git+https://github.com/bertvv/ansible-role-pxeserver.git"
  version: "master"

- name: "bertvv.mailserver"
  src: "git+https://github.com/bertvv/ansible-role-mailserver.git"
  version: "master"

- name: "bertvv.mariadb"
  src: "git+https://github.com/bertvv/ansible-role-mariadb.git"
  version: "master"
