---
- name: Opendkim - install system packages
  package:
    name: "{{ mailserver_opendkim_packages }}"

- name: Opendkim - create config directory
  file:
    path: "{{ opendkim_conf_directory }}"
    state: directory
    owner: opendkim
    group: opendkim

- name: Opendkim - create key directories
  file:
    path: "{{ opendkim_key_directory }}/{{ item }}"
    state: directory
    owner: opendkim
    group: opendkim
  loop: "{{ opendkim_keys }}"

- name: Opendkim - adjust config
  blockinfile:
    path: "{{ opendkim_conf_file }}"
    block: |-
      KeyTable           {{ opendkim_key_table_file }}
      SigningTable       {{ opendkim_signing_table_file }}
      ExternalIgnoreList {{ opendkim_trusted_hosts_file }}
      InternalHosts      {{ opendkim_trusted_hosts_file }}
  notify: Restart opendkim service

- include_tasks: "__opendkim_domain.yml"
  loop: "{{ opendkim_keys }}"
  loop_control:
    loop_var: _opendkim_domain
