# tasks/postfix.yml -- Install and configure Postfix
---
- name: Create group for mail ownership
  group:
    name: "{{ postfix_virtual_mailbox_gname }}"
    gid: "{{ postfix_virtual_mailbox_gid }}"

- name: Create user for mail ownership
  user:
    name: "{{ postfix_virtual_mailbox_uname }}"
    uid: "{{ postfix_virtual_mailbox_uid }}"
    home: "{{ postfix_virtual_mailbox_home }}"
    create_home: yes
    shell: "{{ postfix_virtual_mailbox_shell }}"
    group: "{{ postfix_virtual_mailbox_gname }}"

- name: Install Postfix
  package:
    name: "{{ mailserver_postfix_packages }}"
    state: present

- name: Add postfix to clamav groups
  user:
    name: postfix
    groups:
      - clamav
    append: yes

- name: Add postfix to opendmarc groups
  user:
    name: postfix
    groups:
      - opendmarc
    append: yes
  when: opendmarc_keys is defined

- name: Add postfix to opendkim groups
  user:
    name: postfix
    groups:
      - opendkim
    append: yes
  when: opendkim_keys is defined

- name: Install postfix main configuration
  template:
    src: postfix_main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
  notify: Restart postfix service

- name: Install postfix master configuration
  template:
    src: postfix_master.cf.j2
    dest: "{{ postfix_config_dir }}/master.cf"
  notify: Restart postfix service

- name: Render virtual alias domains
  copy:
    dest: "{{ postfix_virtual_alias_domains_file }}"
    content: |-
      {% for domain in postfix_virtual_aliases_domains %}
      {{ domain }}
      {% endfor %}
  register: _render_virtual_alias_domains

- name: Update virtual alias domains db
  shell: >-
    postmap {{ postfix_virtual_alias_domains }}
  when: _render_virtual_alias_domains is changed
  notify: Restart postfix service

- name: Render virtual aliases
  copy:
    dest: "{{ postfix_virtual_alias_maps_file }}"
    content: |-
      {% for alias in postfix_virtual_aliases %}
      {{ alias.alias }} {{ alias.email }}
      {% endfor %}
  register: _render_virtual_alias
  when: postfix_has_virtual_aliases

- name: Update virtual aliases db
  shell: >-
    postmap {{ postfix_virtual_alias_maps }}
  when: _render_virtual_alias is changed
  notify: Restart postfix service

- name: Render virtual mailboxes
  copy:
    dest: "{{ postfix_virtual_mailbox_maps_file }}"
    content: |-
      {% for alias in postfix_virtual_mailboxes %}
      {{ alias.email }} {{ alias.recipient }}
      {% endfor %}
  register: _render_virtual_mailboxes
  when: postfix_has_virtual_mailboxes

- name: Update virtual mailboxes db
  shell: >-
    postmap {{ postfix_virtual_mailbox_maps }}
  when: _render_virtual_mailboxes is changed
  notify: Restart postfix service

- name: Render transports
  copy:
    dest: "{{ postfix_transport_maps_file }}"
    content: |-
      {% for transport in postfix_transports %}
      {{ transport.domain }} {{ transport.transport }}
      {% endfor %}
  register: _render_transports
  when: postfix_has_transports

- name: Update transports db
  shell: >-
    postmap {{ postfix_transport_maps }}
  when: _render_transports is changed
  notify: Restart postfix service
