---
- name: Sanity checks
  assert:
    that:
      - "{{ postfix_virtual_mailboxes | map(attribute='email') | intersect(postfix_virtual_aliases|map(attribute='alias')) | length == 0 }}"
    msg: >-
       NEVER list a virtual MAILBOX domain name as a virtual ALIAS domain!

- name: Sanity checks
  assert:
    that:
      - >-
        {{
          postfix_virtual_mailboxes | selectattr('email', 'match', '@.*') | map(attribute='email')
          | intersect(postfix_virtual_aliases|map(attribute='alias') | map('regex_replace', '^', '@'))
          | length == 0
        }}
    msg: >-
       NEVER list a virtual MAILBOX domain name as a virtual ALIAS domain!
