---
#
# Based on https://github.com/mattermost/mattermost-docker
#
- import_tasks: "checks.yml"
  when:
    - not _mailserver_uninstall
    - mailserver_enable | bool

- include_tasks: "install.yml"
  when:
    - not _mailserver_uninstall
    - mailserver_enable | bool

- debug:
    msg: Set variable 'mailserver_enable' to 'yes' if you want.
  when:
    - not (mailserver_enable | bool)

- include_tasks: "uninstall.yml"
  when:
    - _mailserver_uninstall
    - not (mailserver_enable | bool)

- meta: flush_handlers