# tasks/postfix.yml -- Install and configure Postfix
---
- name: Sanity checks
  assert:
    that:
      - "{{ postfix_relay_domains | intersect(postfix_virtual_mailboxes|map(attribute='email')) | length == 0 }}"
    msg: >-
      NEVER list a virtual MAILBOX domain name as a relay domain!

- name: Sanity checks
  assert:
    that:
      - "{{ postfix_virtual_mailboxes | map(attribute='email') | intersect(postfix_virtual_aliases|map(attribute='alias')) | length == 0 }}"
    msg: >-
       NEVER list a virtual MAILBOX domain name as a virtual ALIAS domain!

- name: Sanity checks
  assert:
    that:
      - >-
        {{
          postfix_virtual_mailboxes | selectattr('email', 'match', '@.*') | map(attribute='email')
          | intersect(postfix_virtual_aliases|map(attribute='alias') | map('regex_replace', '^', '@'))
          | length == 0
        }}
    msg: >-
       NEVER list a virtual MAILBOX domain name as a virtual ALIAS domain!

- name: Create group for mail ownership
  group:
    name: "{{ postfix_virtual_mailbox_gname }}"
    gid: "{{ postfix_virtual_mailbox_gid }}"

- name: Create user for mail ownership
  user:
    name: "{{ postfix_virtual_mailbox_uname }}"
    uid: "{{ postfix_virtual_mailbox_uid }}"
    home: "{{ postfix_virtual_mailbox_home }}"
    create_home: yes
    shell: "{{ postfix_virtual_mailbox_shell }}"
    group: "{{ postfix_virtual_mailbox_gname }}"

- name: Preseed postfix with debconf
  debconf:
    name: postfix
    vtype: string
    question: "{{ item.question }}"
    value: "{{ item.value }}"
  loop:
    - question: "postfix/mailname"
      value: "{{ postfix_main_domain }}"

    - question: "postfix/main_mailer_type"
      value: "Internet Site"

- name: Install Postfix
  package:
    name: "{{ mailserver_postfix_packages }}"
    state: present

- name: Make SSL directory
  file:
    path: /etc/postfix/ssl
    state: directory
    mode: 0755

- name: Copy SSL key to directory
  copy:
    src: files/
    dest: "{{ postfix_config_dir }}/ssl"

- name: Install postfix main configuration
  template:
    src: postfix_main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
  notify: Restart postfix service

- name: Install postfix master configuration
  template:
    src: postfix_master.cf.j2
    dest: "{{ postfix_config_dir }}/master.cf"
  notify: Restart postfix service

- name: Render virtual mailboxes
  copy:
    dest: "{{ postfix_virtual_mailbox_maps_file }}"
    content: |-
      {% for alias in postfix_virtual_mailboxes %}
      {{ alias.email }} {{ alias.recipient }}
      {% endfor %}
  notify: Restart postfix service

- name: Render virtual aliases
  copy:
    dest: "{{ postfix_virtual_alias_maps_file }}"
    content: |-
      {% for alias in postfix_virtual_aliases %}
      {{ alias.alias }} {{ alias.email }}
      {% endfor %}
  notify: Restart postfix service

- name: Render transports
  copy:
    dest: "{{ postfix_transport_maps_file }}"
    content: |-
      {% for transport in postfix_transports %}
      {{ transport.domain }} {{ transport.transport }}
      {% endfor %}
  notify: Restart postfix service

- name: Render domains
  copy:
    dest: "{{ postfix_domain_maps_file }}"
    content: |-
      {% for domain in postfix_domains %}
      {{ domain }}
      {% endfor %}
  notify: Restart postfix service

- name: Init domains
  shell: >-
    postmap hash:{{ postfix_domain_maps_file }}

- name: Init virtual aliases
  shell: >-
    postmap hash:{{ postfix_virtual_alias_maps_file }}

- name: Init virtual mailboxes
  shell: >-
    postmap hash:{{ postfix_virtual_mailbox_maps_file }}

- name: Init transport
  shell: >-
    postmap hash:/etc/postfix/transport
