# tasks/postfix.yml -- Install and configure Postfix
---
- name: Create group for mail ownership
  group:
    name: "{{ postfix_mail_keeper_group_name }}"
    gid: "{{ postfix_mail_keeper_gid }}"

- name: Create user for mail ownership
  user:
    name: "{{ postfix_mail_keeper_user_name }}"
    uid: "{{ postfix_mail_keeper_uid }}"
    home: "{{ postfix_mail_keeper_home }}"
    create_home: yes
    shell: "{{ postfix_mail_keeper_shell }}"
    group: "{{ postfix_mail_keeper_group_name }}"

- name: Preseed postfix with debconf
  debconf:
    name: postfix
    vtype: string
    question: "{{ item.question }}"
    value: "{{ item.value }}"
  loop:
    - question: "postfix/mailname"
      value: "{{ postfix_main_domain }}"

    - question: "postfix/main_mailer_type"
      value: "Internet Site"

- name: Install Postfix
  package:
    name: "{{ mailserver_postfix_packages }}"
    state: present

- name: Make SSL directory
  file:
    path: /etc/postfix/ssl
    state: directory
    mode: 0755

- name: Copy SSL key to directory
  copy:
    src: files/
    dest: "{{ postfix_config_dir }}/ssl"

- name: Install postfix main configuration
  template:
    src: postfix_main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
  notify: Restart postfix service

- name: Install postfix master configuration
  template:
    src: postfix_master.cf.j2
    dest: "{{ postfix_config_dir }}/master.cf"
  notify: Restart postfix service

- name: Create file local-host-names
  copy:
    dest: /etc/postfix/local-host-names
    content: "{{ postfix_mydomain }}"
  notify: Restart postfix service
