- name: "Load OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
        - main.yml

# Installation of tor
- include: install.yml
- include: config.yml
