---
# See /usr/share/i18n/SUPPORTED
common_lang: 'fr_FR.UTF-8'
common_primary_local: 'fr_FR.UTF-8'
common_secondary_local: 'en_US.UTF-8'
common_language: 'fr'
common_tzdata_areas: 'Europe'
common_tzdata_zones: 'Paris'