---
common_enable_manpages: yes
# See /usr/share/i18n/SUPPORTED
common_lang: 'fr_FR.UTF-8'
common_primary_local: 'fr_FR.UTF-8'
common_secondary_local: 'en_US.UTF-8'
common_language: 'fr'
common_tzdata_areas: 'Europe'
common_tzdata_zones: 'Paris'
common_system_packages:
  - aptitude
  - apt-transport-https
  - bash
  - bash-completion
  - build-essential
  - cpufrequtils
  - cron
  - direnv
  - dnsutils
  - dphys-swapfile
  - findutils
  - git
  - glances
  - grc
  - haveged
  - htop
  - libffi-dev
  - libperl-dev
  - libssl-dev
  - mc
  - minicom
  - openssl
  - powertop
  - python3
  - python3-apt
  - python3-distutils-extra
  - python3-pip
  - python3-setuptools
  - python3-venv
  - rng-tools5
  - rsync
  - screen
  - ssl-cert
  - sudo
  - task-spooler
  - vim
  - wget
common_pip_packages:
  - dnspython
  - cryptography

common_sysctl_vm_swappiness: "20"
common_sysctl_vm_vfs_cache_pressure: "50"
common_sysctl_vm_overcommit_memory: "0"
common_sysctl_vm_overcommit_ratio: "{{ 100 * ((ansible_memtotal_mb - ansible_swaptotal_mb) / ansible_memtotal_mb) }}"
common_sysctl_net_core_wmem_max: "1048576"

common_sysctl_tuning:
  - name: "vm.swappiness"
    value: "{{ common_sysctl_vm_swappiness }}"

  - name: "vm.vfs_cache_pressure"
    value: "{{ common_sysctl_vm_vfs_cache_pressure }}"

  - name: "vm.overcommit_memory"
    value: "{{ common_sysctl_vm_overcommit_memory }}"

  - name: "vm.overcommit_ratio"
    value: "{{ common_sysctl_vm_overcommit_ratio | int | round | int }}"

  - name: "net.core.wmem_max"
    value: "{{ common_sysctl_net_core_wmem_max }}"


# powertop --csv=powertop_report.txt --time=20s
