---
#
# Uninstall flag
#
_mail_uninstall: "{{ mail_uninstall | default(false) | bool }}"
_mail_secret_key_file: "{{ playbook_dir + '/../keys/mail-' + mail_domain + '.key' | realpath }}"

mail_secret_key: "{{ lookup('password', _mail_secret_key_file + ' chars=ascii_letters,digits length=16') }}"
mail_configuration_directory: /etc/mail/mailu

mail_mailu_container_version: "1.7"
mail_mailu_docker_images:
  nginx: "mailu/nginx:{{ mail_mailu_container_version }}"
  admin: "mailu/admin:{{ mail_mailu_container_version }}"
  dovecot: "mailu/dovecot:{{ mail_mailu_container_version }}"
  postfix: "mailu/postfix:{{ mail_mailu_container_version }}"
  rspamd: "mailu/rspamd:{{ mail_mailu_container_version }}"
  radicale: "mailu/radicale:{{ mail_mailu_container_version }}"
  fetchmail: "mailu/fetchmail:{{ mail_mailu_container_version }}"
  roundcube: "mailu/roundcube:{{ mail_mailu_container_version }}"

mail_docker_compose_env_file: /etc/default/mail
mail_expected_directories:
  - "{{ mail_configuration_directory }}"

mail_systemd_service_file: "/lib/systemd/system/mail.service"