---
# store and path
glx_pycharm_professional_prefix_dir: "/var/lib/galaxie"
glx_pycharm_professional_cache_dir: "{{ glx_pycharm_professional_prefix_dir }}/src"
glx_pycharm_professional_opt_dir: "/opt"

# inspirate by: https://github.com/archlinuxcn/repo/blob/master/pycharm-community/PKGBUILD
# https://download.jetbrains.com/python/pycharm-professional-2016.3.tar.gz
glx_pycharm_professional_name: "pycharm-professional"
glx_pycharm_professional_version: "2016.3"
glx_pycharm_professional_desc: "Powerful Python and Django IDE. Professional version."
glx_pycharm_professional_url: "https://www.jetbrains.com/pycharm/"
glx_pycharm_professional_depends:
  - "openjdk-7-jre"
  - "openjdk-7-jre-headless"
  - "libgif4"
  - "ipython"
  - "ipython3"
  - "openssh-client"
  - "python-setuptools"
  - "python-coverage"
  - "vagrant"

glx_pycharm_professional_source: "https://download.jetbrains.com/python/{{ glx_pycharm_professional_name }}-{{ glx_pycharm_professional_version }}.tar.gz"
glx_pycharm_professional_sha256sums: "e988f1704bc89d3972cbba956a93af7b920d1777197f14b5081ebccfcf5991ac"
