---
#
# Based on https://github.com/jitsi/docker-jitsi-meet
#
- import_tasks: "checks.yml"
  when:
    - not _jitsi_meet_uninstall
    - jitsi_meet_enable | bool

- include_tasks: "install.yml"
  when:
    - not _jitsi_meet_uninstall
    - jitsi_meet_enable | bool

- include_tasks: "uninstall.yml"
  when:
    - _jitsi_meet_uninstall
    - not (jitsi_meet_enable | bool)

- meta: flush_handlers