---
- name: "Matrix access token request - Sanity checks"
  assert:
    that:
      - _matrix_user is defined
      - _matrix_user.name is defined
      - _matrix_user.password is defined

- name: "Matrix access token - Requesting for '{{ _matrix_user.name }}'"
  uri:
    url: "https://localhost:8448/_matrix/client/r0/login"
    method: POST
    validate_certs: no
    body:
      type: "m.login.password"
      user: "{{ _matrix_user.name }}"
      password: "{{ _matrix_user.password }}"
    body_format: json
    return_content: yes
  register: _matrix_access_token_request

- name: "Matrix access token - Result stored in matrix_access_tokens['{{ _matrix_user.name }}']"
  set_fact:
    matrix_access_tokens: >-
      {{
        matrix_access_tokens | default({})
        | combine({
          (_matrix_user.name): (_matrix_access_token_request.content | from_json).access_token
        })
      }}
