---
- name: Add project apt signing key
  apt_key:
    url: https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
    state: present

- name: Add project apt repository
  apt_repository:
    repo: "deb https://packages.matrix.org/debian/ {{ ansible_lsb.codename }} main"
    state: present
    filename: matrix
    update_cache: yes

- name: Install system packages
  apt:
    name:
      - matrix-synapse-py3
      - coturn

- name: Add matrix-synapse user to ssl-cert group
  user:
    name: matrix-synapse
    append: yes
    groups:
      - ssl-cert

- name: Set matrix server name Debian-style
  lineinfile:
    dest: /etc/matrix-synapse/conf.d/server_name.yaml
    regex: >-
      ^server_name:.*
    line: >-
      server_name: {{ matrix_server_name }}

- name: Install sydent
  pip:
    name: matrix-sydent

- name: Create sydent directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /usr/local/sydent
    - /var/cache/sydent

- name: Render sydent configuration file
  template:
    src: sydent.conf.j2
    dest: /usr/local/sydent/sydent.conf
  notify: Restart sydent service

- name: Render sydent service file
  template:
    src: sydent.service.j2
    dest: /lib/systemd/system/matrix-sydent.service
  notify: Restart sydent service

- name: Render matrix configuration file
  template:
    src: "matrix-homeserver.yaml.j2"
    dest: /etc/matrix-synapse/homeserver.yaml
  notify: Restart matrix service

- name: Render nginx configuration file
  template:
    src: "matrix-nginx.site.conf.j2"
    dest: "{{ matrix_nginx_config_directory }}/matrix.conf"
  notify: Restart nginx service

- name: Add yarn apt signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn apt repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
    filename: matrix
    update_cache: yes

- name: Install Yarn
  apt:
    name:
      - yarn
      - nodejs
      - npm

- name: Clone riot web sources
  git:
    repo: "https://github.com/vector-im/riot-web.git"
    dest: /usr/src/riot-web
    version: "v1.5.12"

- name: Install riot-web dependencies
  shell: >-
    yarn install
  args:
    chdir: /usr/src/riot-web
    creates: /usr/src/riot-web/dist/riot-v1.5.12.tar.gz

- name: Install riot-web dependencies
  shell: >-
    yarn dist
  args:
    chdir: /usr/src/riot-web
    creates: /usr/src/riot-web/dist/riot-v1.5.12.tar.gz

- name: Expand riot-web dist
  unarchive:
    src: /usr/src/riot-web/dist/riot-v1.5.12.tar.gz
    remote_src: yes
    dest: /var/www/
    creates: /var/www/riot-v1.5.12

- name: Configure riot-web
  template:
    src: "riot-web.config.json.j2"
    dest: "/var/www/riot-v1.5.12/config.json"
  notify: Restart nginx service

- apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
    update_cache: yes

- apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create dimension configuration directory
  file:
    path: /etc/dimension
    state: directory

- name: Render dimension configuration file
  template:
    src: dimension.conf.j2
    dest: /etc/dimension/config.yaml

- name: Render nginx configuration file
  template:
    src: "riot.nginx.conf.j2"
    dest: "{{ matrix_nginx_config_directory }}/riot.conf"
  notify: Restart nginx service

- name: Render coturn configuration file
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
  notify: Restart coturn service

- name: Enable system services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - matrix-synapse
    - nginx
    - coturn
