---
# dpkg-reconfigure mysql-server-5.5 and copy/past content of ~/keystore-{{ ansible_hostname }}
# dpkg-reconfigure mysql-server-core-5.6
- name: Set MySQL root password before installing
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{galaxie_mysql_server_root_db_password | quote}}"
    vtype: "password"
  changed_when: False

- name: Confirm MySQL root password before installing
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{galaxie_mysql_server_root_db_password | quote}}"
    vtype: "password"
  changed_when: False

- name: Install MySQL
  apt:
    package: "{{ item }}"
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb
  notify:
    - restart mysql

- name: copy .my.cnf file with root password credentials
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Setup MySQL root password
  mysql_user:
    name: root
    password: "{{ galaxie_mysql_server_root_db_password }}"
    host: "{{ item }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: remove the test database
  mysql_db:
    name: test
    state: absent

- name: start mysql-server at startup
  service:
    name: mysql
    state: started
    enabled: true
