---
#
# Based on https://github.com/mattermost/mattermost-docker
#
- import_tasks: "checks.yml"
  when:
    - not _chat_uninstall
    - chat_enable | bool

- include_tasks: "install.yml"
  when:
    - not _chat_uninstall
    - chat_enable | bool

- include_tasks: "uninstall.yml"
  when:
    - _chat_uninstall
    - not (chat_enable | bool)

- meta: flush_handlers