- name: "Load OS stretch specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.stretch.yml"
        - main.yml

# Installation of tor
- include: install.yml
- include: config.yml
