---
- name: Create calendar group
  group:
    name: "{{ calendar_user.group }}"
    gid: "{{ calendar_user.gid }}"

- name: Create calendar user
  user:
    name: "{{ calendar_user.name }}"
    uid: "{{ calendar_user.uid }}"
    home: "{{ calendar_user.home }}"
    group: "{{ calendar_user.group }}"
    groups: "{{ calendar_user.groups }}"
    shell: "{{ calendar_user.shell | default('/bin/false') }}"

- name: Create expected directories
  file:
    path: "{{ item }}"
    owner: "{{ calendar_user.name }}"
    group: "{{ calendar_user.group }}"
    state: directory
  loop: "{{ calendar_expected_directories }}"

- name: Render logging configuration
  template:
    src: radicale.logging.j2
    dest: /etc/radicale/logging
  notify: Restart calendar service

- name: Render main configuration
  template:
    src: radicale.config.j2
    dest: /etc/radicale/config
  notify: Restart calendar service

- name: Render rights configuration
  template:
    src: radicale.rights.j2
    dest: /etc/radicale/rights
  notify: Restart calendar service

- name: Render rproxy service configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/calendar.conf
  notify: Reload nginx service

- name: Render docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ calendar_config_dir }}/docker-compose.yml"
  notify:
    - Restart calendar service

- name: Render calendar systemd service
  template:
    src: "systemd.service.j2"
    dest: "{{ calendar_systemd_service_file }}"
  register: _calendar_systemd_service_render
  notify:
    - Restart calendar service

- name: Start calendar service
  systemd:
    name: calendar
    state: started
    daemon_reload: "{{ _calendar_systemd_service_render is changed }}"
