# roles/mailserver/defaults/main.yml
---
postfix_main_domain: 'mail.localhost.local'

postfix_home_mailbox: 'mail/'

spamassassin_packages:
  - spamassassin

clamav_packages:
  - clamav-server
  - clamav-data
  - clamav-update
  - clamav-filesystem
  - clamav
  - clamav-scanner-systemd
  - clamav-devel
  - clamav-lib
  - clamav-server-systemd

postfix_mynetwork:
  - 172.16.0.0/16

postfix_virtual_mailbox_gname: vmail
postfix_virtual_mailbox_gid: 5000

postfix_virtual_mailbox_uname: vmail
postfix_virtual_mailbox_uid: 5000
postfix_virtual_mailbox_home: /home/vmail
postfix_virtual_mailbox_shell: /usr/bin/nologin

postfix_virtual_alias_maps_file: /etc/postfix/virtual_alias_maps
postfix_virtual_mailbox_maps_file: /etc/postfix/virtual_mailbox_maps
postfix_transport_maps_file: /etc/postfix/transport

postfix_virtual_alias_maps: "hash:{{ postfix_virtual_alias_maps_file }}"
postfix_virtual_mailbox_maps: "hash:{{ postfix_virtual_mailbox_maps_file }}"
postfix_transport_maps: "hash:{{ postfix_transport_maps_file }}"

postfix_relay_domains:
  - localhost

postfix_transports: []
# - domain: "example.com"
#   transport: "smtp:internal.example.com"
postfix_virtual_aliases: []
# - alias: "info-alias@example.com"
#   email: "info@example.com"
postfix_virtual_mailboxes: []
# - email: "info@example.com"
#   recipient: "example.com/info"


postfix_virtual_mailbox_domains: "{{ postfix_relay_domains }}"
postfix_mailbox_base: "{{ postfix_virtual_mailbox_home }}"

postfix_virtual_uid_maps: "static:{{ postfix_virtual_mailbox_uid }}"
postfix_virtual_gid_maps: "static:{{ postfix_virtual_mailbox_gid }}"
postfix_virtual_minimum_uid: "{{ postfix_virtual_mailbox_uid }}"

postfix_virtual_mailbox_limit: 512000000

# postfix_smtpd_tls_cert_file: "/etc/ssl/private/your.domain.crt"
# postfix_smtpd_tls_key_file: "/etc/ssl/private/your.domain.key"