# roles/mailserver/defaults/main.yml
---
postfix_main_domain: 'mail.localhost.local'

postfix_home_mailbox: 'mail/'

spamassassin_packages:
  - spamassassin

clamav_packages:
  - clamav-server
  - clamav-data
  - clamav-update
  - clamav-filesystem
  - clamav
  - clamav-scanner-systemd
  - clamav-devel
  - clamav-lib
  - clamav-server-systemd

postfix_mynetwork:
  - 172.16.0.0/16

postfix_mail_keeper_group_name: vmail
postfix_mail_keeper_gid: 5000

postfix_mail_keeper_user_name: vmail
postfix_mail_keeper_uid: 5000
postfix_mail_keeper_home: /home/vmail
postfix_mail_keeper_shell: /usr/bin/nologin
