---
- import_tasks: _groups.yml

- import_tasks: _rotation.yml

- include_tasks: "_init_{{ item }}_salt.yml"
  loop: "{{ system_users_supported_hash }}"

- name: Generate and store password and hashes
  delegate_to: localhost
  become: no
  copy:
    dest: "{{ system_users_hashed_password_file }}"
    content: >-
      {{ 
        lookup('password', system_users_clear_password_file)
        | password_hash(item[1], system_users_hash_salt[item[1]]) 
      }}
  loop: "{{ system_users_expecting_rotation | product(system_users_supported_hash) | list }}"

- name: Create system users
  user:
    name: "{{ current_user.uname }}"
    uid: "{{ current_user.uid }}"
    groups: "{{ current_user.groups | default(omit) }}"
    shell: "{{ current_user.shell | default(system_users_default_shell) }}"
    home: "{{ current_user.home | default(system_users_default_home) }}"
    password: "{{ lookup('file', system_users_prefered_hash) }}"
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user

- name: Authorize user key
  authorized_key:
    user: "{{ current_user.uname }}"
    key: "{{ current_user.authorized_key | default('') }}"
    exclusive: yes
    manage_dir: yes
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user
