---
- name: Create system groups
  group:
    name: "{{ current_group.gname }}"
    gid: "{{ current_group.gid }}"
  loop: "{{ system_users_groups }}"
  loop_control:
    loop_var: current_group

- name: Create system parent groups for each user
  group:
    name: "{{ current_user.uname }}"
    gid: "{{ current_user.uid }}"
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user

- include_tasks: "_init_{{ item }}_salt.yml"
  loop: "{{ system_users_supported_hash }}"

- name: Erase old password
  delegate_to: localhost
  become: no
  file:
    path: "{{ system_users_local_passwords_dir }}/{{ item.uname }}.password"
    state: absent
  loop: "{{ system_users | selectattr('rotate', 'defined') | selectattr('rotate') | list }}"

- name: Generate and store password and hashes
  delegate_to: localhost
  become: no
  copy:
    dest: "{{ system_users_local_passwords_dir }}/{{ item[0].uname }}.password.{{ item[1] }}"
    content: >-
      {{ 
        lookup(
          'password', 
          system_users_local_passwords_dir + '/' + item[0].uname + '.password'
        )
        | password_hash(item[1], system_users_hash_salt[item[1]]) 
      }}
  loop: "{{ system_users | product(system_users_supported_hash) | list }}"
  
- name: Create system users
  user:
    name: "{{ current_user.uname }}"
    uid: "{{ current_user.uid }}"
    groups: "{{ current_user.groups | default(omit) }}"
    shell: "{{ current_user.shell | default(system_users_default_shell) }}"
    home: "{{ current_user.home | default(system_users_default_home) }}"
    password: "{{ lookup('file', system_users_prefered_hash) }}"
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user

- name: Authorize user key
  authorized_key:
    user: "{{ current_user.uname }}"
    key: "{{ current_user.authorized_key | default('') }}"
    exclusive: yes
    manage_dir: yes
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user
