---
- include_tasks: ssh_client.yml

- include_tasks: ssh_server.yml

- name: Disable local mail checking after login
  lineinfile:
    dest: /etc/pam.d/sshd
    backrefs: yes
    state: present
    regexp: "^session    optional     pam_mail.so standard noenv"
    line: "#session    optional     pam_mail.so standard noenv \\# [1]"

- meta: flush_handlers