---
- name: Fine tune openssh server configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.key }} "
    line: "{{ item.key }} {{ item.value }}"
    insertafter: "{{ item.key }} "
    state: present
    backup: yes
    validate: "/usr/sbin/sshd -T -f %s"
  loop:
    - { key: "ListenAddress",   value: "0.0.0.0" }
    - { key: "Protocol",        value: "2" }
    - { key: "DebianBanner",    value: "no" }
    - { key: "PrintLastLog",    value: "yes" }
    - { key: "SyslogFacility",  value: "AUTH" }
    - { key: "LogLevel",        value: "INFO" }
    - { key: "LoginGraceTime",  value: "60" }
    - { key: "StrictModes",     value: "yes" }
    - { key: "TCPKeepAlive",    value: "yes" }
    - { key: "Compression ",     value: "yes" }
    - { key: "IgnoreRhosts",    value: "yes" }
    - { key: "PermitRootLogin",     value: "no" }
    - { key: "RSAAuthentication",   value: "no" }
    - { key: "ClientAliveInterval", value: "300" }
    - { key: "ClientAliveCountMax", value: "2" }
    - { key: "PubkeyAuthentication",  value: "yes" }
    - { key: "AuthorizedKeysFile",    value: "%h/.ssh/authorized_keys" }
    - { key: "RhostsRSAAuthentication", value: "no" }
    - { key: "HostbasedAuthentication", value: "no" }
    - { key: "PermitEmptyPasswords",    value: "no" }
    - { key: "PasswordAuthentication",  value: "no" }
    - { key: "GSSAPIAuthentication",    value: "no" }
    - { key: "ChallengeResponseAuthentication", value: "no" }
  notify:
    - restart sshd service

- include_tasks: ssh_allies.yml
  when:
    - groups[clan_allies_group] is defined
    - groups[clan_allies_group] | length > 0