---
# Ref Doc: https://patrickmn.com/aside/how-to-keep-alive-ssh-sessions/
- name: Fine tune ssh config
  lineinfile:
    dest: "/etc/ssh/ssh_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter|default(omit) }}"
  loop:
    - regexp: "^ *ServerAliveCountMax.*|^# *ServerAliveCountMax.*"
      line: "    ServerAliveCountMax 2"
      # Ref Doc: https://patrickmn.com/aside/how-to-keep-alive-ssh-sessions/
    - regexp: "^ *ServerAliveInterval.*|^# *ServerAliveInterval.*"
      line: "    ServerAliveInterval 300"
    - regexp: "^ *CompressionLevel.*|^# *CompressionLevel.*"
      line: "    CompressionLevel 9"
    - regexp: "^ *Protocol.*|^# *Protocol.*"
      line: "    Protocol 2"
      # Fix for CVE-2016-0777
    - regexp: "^ *UseRoaming.*"
      line: "    UseRoaming no"
      insertafter: "^Host *"
  notify: restart ssh service
