- name: "Load OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.{{ ansible_distribution_major_version }}.yml"
        - main.yml
      paths:
        - ../vars

# Installation of TeamSpeak 3 Server
- include: install.yml


# Perform the running of handlers now
# So we can do "Reload systemd" (and possibly queued clean-up)
# before we start using the new/changed .service file.
- meta: flush_handlers
# Make sure TeamSpeak 3 Server is started and enabled
- name: Enable and start TeamSpeak 3 Server
  service:
    name: teamspeak3-server
    state: started
    enabled: yes

# Display Teamspeak 3 Server Token and Password if this is a new installation
# (a new installation has no userdata, and this is checked for in install.yml)
- include: display.yml
  when: userdata.stat.exists is defined and userdata.stat.exists == False