---
- name: Install HTTPS transport for APT
  apt:
    pkg:
      - apt-transport-https
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Add the gpg key used to sign the packages
  apt_key:
    url: "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    state: present
  when: ansible_distribution == "Debian"

- name: Add deb repository
  apt_repository:
    filename: "torproject.list"
    repo: "deb https://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main"
    update_cache: no
    state: present
  when: ansible_distribution == "Debian"

- name: Add deb-src repository
  apt_repository:
    filename: "torproject.list"
    repo: "deb-src https://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main"
    update_cache: no
    state: present
  when: ansible_distribution == "Debian"

- name: Update APT repositories then Install tor and tor debian keyring
  apt:
    pkg:
      - tor
      - deb.torproject.org-keyring
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

