---
- name: Check {{ glx_nacl_source_dir }} directory
  file:
    path: "{{ glx_nacl_source_dir }}"
    state: directory
  changed_when: false

- name: Delete "{{ glx_nacl_source_dir }}/{{ glx_nacl_archive_filename }}"
  file:
    path: "{{ glx_nacl_source_dir }}/{{ glx_nacl_archive_filename }}"
    state: absent
  when: glx_nacl_force_install
  changed_when: false

- name: Copy file with owner and permissions
  copy:
    src: "files/{{ glx_nacl_archive_filename }}"
    dest: "{{ glx_nacl_source_dir }}/{{ glx_nacl_archive_filename }}"
    checksum: "{{ glx_nacl_download_file_sha1sum }}"
    owner: "root"
    group: "root"
    mode: "0644"
  changed_when: false

- name: Delete "{{ glx_nacl_source_dir }}/{{ glx_nacl_app_name }}-{{ glx_nacl_app_version }}" directory
  file:
    path: "{{ glx_nacl_source_dir }}/{{ glx_nacl_app_name }}-{{ glx_nacl_app_version }}"
    state: absent
  when: glx_nacl_force_install
  changed_when: false

- name: Unarchive {{ glx_nacl_source_dir }}/{{ glx_nacl_archive_filename }}
  unarchive:
    src: "{{ glx_nacl_source_dir }}/{{ glx_nacl_archive_filename }}"
    dest: "{{ glx_prefix_dir }}/lib"
    copy: no
  changed_when: false

- name: Install
  command: ./do
  args:
    chdir: "{{ glx_prefix_dir }}/lib/{{ glx_nacl_app_name }}-{{ glx_nacl_app_version }}"
  changed_when: false
