---

- name: Ensure {{ glx_djbdnscurses6_tinydns_env_ROOT }} directory exit
  file:
    path: "{{ glx_djbdnscurses6_tinydns_env_ROOT }}"
    state: directory

- name: Ensure {{ glx_djbdnscurses6_tinydns_env_ROOT }}/zone directory exist
  file:
    path: "{{ glx_djbdnscurses6_tinydns_env_ROOT }}/zones"
    state: directory

- name: Copy tinydns.conf in {{ glx_djbdnscurses6_tinydns_env_ROOT }}
  template:
    src: "etc/tinydns/{{ item }}.j2"
    dest: "{{ glx_djbdnscurses6_tinydns_env_ROOT }}/{{ item }}"
  with_items:
    - "tinydns.conf"
    - "Makefile"

- name: Copy tinydns.service in /lib/systemd/system/
  template:
    src: "services/systemd/{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
  with_items:
    - "tinydns.service"

- name: Reload systemd
  command: systemctl daemon-reload
  changed_when: false