---
- name: Ensure group "{{ glx_djbdnscurses6_tinydns_group }}" exists
  group:
    name: "{{ glx_djbdnscurses6_tinydns_group }}"
    state: present

- name: Add the user "{{ glx_djbdnscurses6_tinydns_user }}"
  user:
    name: "{{ glx_djbdnscurses6_tinydns_user }}"
    group: "{{ glx_djbdnscurses6_tinydns_group }}"
    shell: /usr/sbin/nologin

- name: Check directory {{ glx_djbdnscurses6_sysprefix_dir }}/tinydns.
  stat:
    path: "{{ glx_djbdnscurses6_sysprefix_dir }}/tinydns"
  register: tinydns_conf_directory

- name: Create setting inside {{ glx_djbdnscurses6_sysprefix_dir }}/tinydns
  command: "/usr/local/bin/tinydns-conf {{ glx_djbdnscurses6_tinydns_user }} {{ glx_djbdnscurses6_dnslog_group }} {{ glx_djbdnscurses6_sysprefix_dir }}/tinydns {{ ansible_default_ipv4.address }}"
  when: tinydns_conf_directory.stat.exists == false

- name: Copy tinydns.service in /lib/systemd/system/
  template:
    src: "services/systemd/{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
  with_items:
    - "tinydns.service"

- name: Reload systemd
  command: systemctl daemon-reload