---

- name: Ensure {{ glx_djbdnscurses6_dnscache_env_ROOT }} directory exit
  file:
    path: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}"
    state: directory
    owner: root
    group: root
    mode: '3755'

- name: Ensure {{ glx_djbdnscurses6_dnscache_env_ROOT }}/ip directory exist
  file:
    path: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}/ip"
    state: directory
    owner: root
    group: root
    mode: '2755'

- name: Copy files in {{ glx_djbdnscurses6_dnscache_env_ROOT }}/ip
  template:
    src: "etc/dnscache/ip/{{ item }}.j2"
    dest: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}/ip/{{ item }}"
    mode: '0644'
  with_items:
    - "127.0.0.1"
    - "::1"

- name: Ensure {{ glx_djbdnscurses6_dnscache_env_ROOT }}/servers directory exist
  file:
    path: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}/servers"
    state: directory
    owner: root
    group: root
    mode: '2755'

- name: Ensure {{ glx_djbdnscurses6_dnscache_env_ROOT }}/servers/@
  template:
    src: "etc/dnscache/servers/@.j2"
    dest: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}/servers/@"
    mode: '0644'

- name: Ensure {{ glx_djbdnscurses6_dnscache_env_ROOT }}/dnscache.conf
  template:
    src: "etc/dnscache/dnscache.conf.j2"
    dest: "{{ glx_djbdnscurses6_dnscache_env_ROOT }}/dnscache.conf"
    mode: '0644'

- name: Ensure /lib/systemd/system/dnscache.service
  template:
    src: "services/systemd/dnscache.service.j2"
    dest: "/lib/systemd/system/dnscache.service"

- name: Reload systemd
  command: systemctl daemon-reload
  changed_when: false