---
- name: Check {{ glx_djbdnscurses6_source_dir }} directory
  file:
    path: "{{ glx_djbdnscurses6_source_dir }}"
    state: directory
  changed_when: false

- name: Delete "{{ glx_djbdnscurses6_source_dir }}/{{ glx_djbdnscurses6_archive_filename }}"
  file:
    path: "{{ glx_djbdnscurses6_source_dir }}/{{ glx_djbdnscurses6_archive_filename }}"
    state: absent
  when: glx_djbdnscurses6_force_install
  changed_when: false

- name: Copy file with owner and permissions
  copy:
    src: "files/{{ glx_djbdnscurses6_archive_filename }}"
    dest: "{{ glx_djbdnscurses6_source_dir }}/{{ glx_djbdnscurses6_archive_filename }}"
    checksum: "1dfa9d0cd9ee0af18e4643b6953e9074db3dcc92"
    owner: "root"
    group: "root"
    mode: "0644"
  changed_when: false

- name: Delete "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}" directory
  file:
    path: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}"
    state: absent
  changed_when: false

- name: Unarchive {{ glx_djbdnscurses6_source_dir }}/{{ glx_djbdnscurses6_archive_filename }}
  unarchive:
    src: "{{ glx_djbdnscurses6_source_dir }}/{{ glx_djbdnscurses6_archive_filename }}"
    dest: "{{ glx_slashpackage_dir }}"
    copy: no
  changed_when: false

- name: Copy conf-* in to {{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}/
  template:
    src: "{{ item }}.j2"
    dest: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}/{{ item }}"
  with_items:
    - "conf-axfrdns"
    - "conf-cc"
    - "conf-dnscache"
    - "conf-home"
    - "conf-ld"
    - "conf-man"
    - "conf-nacl"
    - "conf-qlibs"
    - "conf-rbldns"
    - "conf-tinydns"
    - "conf-walldns"
  changed_when: false

- name: Compile {{ glx_djbdnscurses6_app_name }}
  command: package/compile
  args:
    chdir: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}"
  changed_when: false

- name: Upgrade {{ glx_djbdnscurses6_app_name }}
  command: package/upgrade
  args:
    chdir: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}"
  changed_when: false

- name: Legacy {{ glx_djbdnscurses6_app_name }}
  command: package/legacy
  args:
    chdir: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}"
  changed_when: false

- name: Clean Man
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/share/man/man8/axfr-get.8.gz"
    - "/usr/share/man/man8/tinydns-edit.8.gz"
    - "/usr/share/man/man1/dnsqr.1.gz"
    - "/usr/share/man/man8/tinydns-data.8.gz"
    - "/usr/share/man/man1/dnsip.1.gz"
    - "/usr/share/man/man8/rbldns-data.8.gz"
    - "/usr/share/man/man8/walldns.8.gz"
    - "/usr/share/man/man5/tinydns-log.5.gz"
    - "/usr/share/man/man8/axfrdns-conf.8.gz"
    - "/usr/share/man/man8/axfrdns.8.gz"
    - "/usr/share/man/man1/dnstrace.1.gz"
    - "/usr/share/man/man5/qualification.5.gz"
    - "/usr/share/man/man5/dnscache-log.5.gz"
    - "/usr/share/man/man1/dnsmx.1.gz"
    - "/usr/share/man/man8/walldns-conf.8.gz"
    - "/usr/share/man/man1/dnsipq.1.gz"
    - "/usr/share/man/man8/rbldns.8.gz"
    - "/usr/share/man/man8/tinydns-conf.8.gz"
    - "/usr/share/man/man8/tinydns.8.gz"
    - "/usr/share/man/man1/dnsfilter.1.gz"
    - "/usr/share/man/man1/dnsname.1.gz"
    - "/usr/share/man/man8/dnscache.8.gz"
    - "/usr/share/man/man8/rbldns-conf.8.gz"
    - "/usr/share/man/man1/dnsq.1.gz"
    - "/usr/share/man/man1/dnstxt.1.gz"
    - "/usr/share/man/man8/dnscache-conf.8.gz"
  changed_when: false

- name: Man {{ glx_djbdnscurses6_app_name }}
  command: package/man
  args:
    chdir: "{{ glx_slashpackage_dir }}/net/{{ glx_djbdnscurses6_app_name }}/{{ glx_djbdnscurses6_app_name }}-{{ glx_djbdnscurses6_app_version }}"
  changed_when: false
