---
- name: ucspi-tcp-ipv6 | uninstall ucspi-tcp-ipv6 and ucspi-tcp packages
  apt:
    pkg:
      - ucspi-tcp-ipv6
      - ucspi-tcp
      - ucspi-proxy
      - ucspi-unix
    state: absent

- name: ucspi-tcp-ipv6 | install packages for ucspi-ssl building
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - libperl-dev
    state: present

- name: ucspi-tcp-ipv6 | check {{ glx_slashpackage_dir }} directory
  file:
    path: "{{ glx_slashpackage_dir }}"
    state: directory
    mode: 1755

- name: ucspi-tcp-ipv6 | check {{ glx_ucspi_tcp6_source_dir }} directory
  file:
    path: "{{ glx_ucspi_tcp6_source_dir }}"
    state: directory

- name: ucspi-tcp-ipv6 | delete "{{ glx_ucspi_tcp6_archive_path }}"
  file:
    path: "{{ glx_ucspi_tcp6_archive_path }}"
    state: absent
  when: glx_ucspi_tcp6_force_install

- name: ucspi-tcp-ipv6 | get "{{ glx_ucspi_tcp6_download_file }}"
  get_url:
    url: "{{ glx_ucspi_tcp6_download_file }}"
    dest: "{{ glx_ucspi_tcp6_source_dir }}"
    sha256sum: "{{ glx_ucspi_tcp6_download_file_sha256sum }}"
  register: glx_ucspi_tcp6_download

- name: ucspi-tcp-ipv6 | delete "{{ glx_ucspi_tcp6_build_directory }}" directory
  file:
    path: "{{ glx_ucspi_tcp6_build_directory }}"
    state: absent
  when: glx_ucspi_tcp6_download.changed

- name: ucspi-tcp-ipv6 | unarchive {{ glx_ucspi_tcp6_downloaded_file }}
  unarchive:
    src: "{{ glx_ucspi_tcp6_downloaded_file }}"
    dest: "{{ glx_slashpackage_dir }}"
    copy: no
  when: glx_ucspi_tcp6_download.changed

- name: ucspi-tcp-ipv6 | fixe permissions
  file:
    path: "{{ glx_ucspi_tcp6_build_directory }}"
    owner: "root"
    group: "root"
    recurse: yes
  when: glx_ucspi_tcp6_download.changed

# send conf-* files
- name: ucspi-tcp-ipv6 | check conf-*
  template:
    src: "{{ item }}.j2"
    dest: "{{ glx_ucspi_tcp6_build_directory }}/{{ item }}"
  with_items:
    - "conf-home"
    - "conf-qlibs"

- name: ucspi-tcp-ipv6 | package/install
  shell: package/install
    chdir="{{ glx_ucspi_tcp6_build_directory }}"
  when: glx_ucspi_tcp6_download.changed
