---

- name: fehqlibs | check {{ glx_fehqlibs_source_dir }} directory
  file:
    path: "{{ glx_fehqlibs_source_dir }}"
    state: directory

- name: fehqlibs | delete "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_archive_filename }}"
  file:
    path: "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_archive_filename }}"
    state: absent
  when: glx_fehqlibs_force_install

- name: fehqlibs | get "{{ glx_fehqlibs_download_file }}"
  get_url:
    url: "{{ glx_fehqlibs_download_file }}"
    dest: "{{ glx_fehqlibs_source_dir }}"
    sha256sum: "{{ glx_fehqlibs_download_file_sha256sum }}"
  register: glx_fehqlibs_source_download

- name: fehqlibs | delete "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}" directory
  file:
    path: "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}"
    state: absent
  when: glx_fehqlibs_source_download.changed

- name: fehqlibs | unarchive {{ glx_fehqlibs_source_download.dest }}
  unarchive:
    src: "{{ glx_fehqlibs_source_download.dest }}"
    dest: "{{ glx_fehqlibs_source_dir }}"
    copy: no
  when: glx_fehqlibs_source_download.changed

- name: fehqlibs | check DEB_BUILD_ARCH
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  when: ansible_os_family == "Debian"
  register: DEB_BUILD_ARCH
  changed_when: false

# send conf-* files
- name: fehqlibs | check conf-*
  template:
    src: "{{ item }}.j2"
    dest: "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}-{{ glx_fehqlibs_app_version }}/{{ item }}"
  with_items:
    - "conf-build"

- name: fehqlibs | install locate
  apt:
    pkg:
      - locate
    state: present
  when: ansible_os_family == "Debian"

- name: fehqlibs | update locate db
  shell: updatedb
  changed_when: false

- name: fehqlibs | check for sys/select.h
  shell: locate sys/select.h
  when: ansible_os_family == "Debian"
  register: sys_select_path
  changed_when: false

- name: fehqlibs | configure SELECT_H="{{ sys_select_path.stdout }}"
  replace:
    dest: "{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}-{{ glx_fehqlibs_app_version }}/configure"
    regexp: '^SELECT_H="/usr/include/sys/select.h"'
    replace: 'SELECT_H="{{ sys_select_path.stdout }}"'

- name: fehqlibs | build {{ glx_fehqlibs_app_name }} on "{{ glx_fehqlibs_source_dir }}" directory
  shell: make
    chdir="{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}-{{ glx_fehqlibs_app_version }}"
  changed_when: false

- name: fehqlibs | install {{ glx_fehqlibs_app_name }}
  shell: make setup check
    chdir="{{ glx_fehqlibs_source_dir }}/{{ glx_fehqlibs_app_name }}-{{ glx_fehqlibs_app_version }}"
  changed_when: false