---

- name: Check Figlet status
  tags: banner
  apt:
    pkg:
      - figlet
    state: present

- name: Copy {{ banner_font_filename }} to {{ banner_figlet_font_dir }}/
  tags: banner
  copy:
    src: "{{ banner_font_filename }}"
    dest: "{{ banner_figlet_font_dir }}/{{ banner_font_filename }}"
    owner: root
    group: root
    mode: 0644

- name: Generate figlet banner
  tags: banner
  command: /usr/bin/figlet -c -w 80 -f {{ banner_font_name }} '{{ banner_text }}'
  register: banner_figlet_result
  changed_when: false

- name: Configure message of the day
  tags: banner
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: /etc/issue.* are empty
  tags: banner
  template:
    src: empty.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/issue
    - /etc/issue.net
    - /etc/banner.dynamic
