---
- name: 'Check if docker is installed'
  group:
    name: docker
  check_mode: yes
  changed_when: no
  register: docker_group_existence_check

- set_fact:
    docker_group_exists: "{{ docker_group_existence_check is not changed }}"

- command: >-
    which dockerd
  register: dockerd_existence_check
  changed_when: no
  failed_when: no

- set_fact:
    dockerd_exists: "{{ dockerd_existence_check.rc == 0 }}"
