---
galaxy_info:
  author: Tuux
  description: OpenSSH daemon tuning
  company: Galaxie
  issue_tracker_url: https://gitlab.com/Tuuux/galaxie/issues
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - system

dependencies: []
