---

- name: install packages
  apt:
    pkg: "{{ basic_packages }}"
    state: present

- name: create dir for app user {{ app_user }}
  file: 
    path: "{{ app_user_home | dirname }}"
    recurse: yes
    state: directory

- name: create app user {{ app_user }}
  user: 
    name: "{{ app_user }}"
    comment: "For app {{ app_user }}"
    groups: sudo
    password: "{{ app_user_password }}"
    update_password: on_create
    home: "{{ app_user_home }}"
    createhome: yes
    shell: "{{ app_user_shell }}"

- name: install yarn gpg key for repository
  apt_key:
    url: "{{ yarn_gpg_url }}"
    state: present

- name: set up yarn repository
  lineinfile:
    line: "{{ yarn_repo_line }}"
    path: "{{ yarn_repo_file }}"
    mode: 0644
    owner: "root"
    group: "root"
    create: yes

- name: install yarn package
  apt:
    update_cache: yes
    name: yarn
    state: present

- name: install remaining packages
  apt:
    pkg: "{{ remaining_packages }}"
    state: present
  tags: remaining_packages
 
- name: get the package facts
  package_facts:
  register: mypackages
  tags: mypack

- name: Is version ok ?
  fail: 
    msg: "The version of {{ item.name }} is {{ item.version }} which is before {{ item.limit }}"
  when: item.version | int < item.limit | int
  with_items:
    - name: g++
      version: "{{ mypackages.ansible_facts.packages['g++'][0].version | regex_replace('.*:([0-9])([0-9\\.]+).*','\\1') }}"
      limit: 5
    - name: ffmpeg
      version: "{{ mypackages.ansible_facts.packages['ffmpeg'][0].version | regex_replace('.*:([0-9])([0-9\\.]+).*','\\1') }}"
      limit: 3
  tags: mypack

- name: create required directories
  file:
    state: directory
    path: "{{ app_user_home }}/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  with_items: "{{ special_directories }}"
  tags: spedirs

