---

- name: set up systemd service unit for peertube
  copy:
    remote_src: yes
    src: "{{ peertube_service_src }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: set up service unit peertube and start it up
  systemd:
    enabled: yes
    name: "{{ peertube_service_name }}"
    state: started

- name: Wait Peertube starting
  pause:
    seconds: 30
    prompt: |
      .   
      .
      .
      .   Wait a minute
      .
      .   Peertube is starting
      .
      .   Relax yourself, inspire, take a moment to think about your life
      .   Release the tense, breath, imagine a butterfly,
      .
      .   Have a kit-kat...
      .
      .

