---

- name: Check desired packages
  apt:
    pkg:
      - bash-completion
      - dnsutils
      - htop
      - git
      - wget
      - mc
      - rsync
      - screen
      - minicom
      - task-spooler
      - cron
      - findutils
      - grc
      - glances
    state=present

- name: Check undesired packages
  apt:
    pkg:
      - ntpdate
      - nfs-common
      - nfs-kernel-server
      - rpcbind
      - emacs
      - samba
      - samba-co
    state: absent
    purge: yes

