---
dependency:
  name: galaxy

driver:
  name: delegated


platforms:
  - name: debian-stretch
    ami_owner: "379101102735"
    ami_name: "debian-stretch-hvm-x86_64-gp2*"
    instance_type: t2.medium
    user: admin

lint:
  name: yamllint
  options:
    config-file: "${MOLECULE_PROJECT_DIRECTORY}/molecule/.yamllint"

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: "${MOLECULE_PROJECT_DIRECTORY}/molecule/utils/delegated_create.yml"
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/molecule/utils/delegated_prepare.yml"
    converge: "${MOLECULE_PROJECT_DIRECTORY}/molecule/utils/delegated_converge.yml"
    destroy: "${MOLECULE_PROJECT_DIRECTORY}/molecule/utils/delegated_destroy.yml"

verifier:
  name: testinfra
  lint:
    name: flake8
