---
- import_tasks: "checks.yml"
  when:
    - not _bind_uninstall
    - bind_enable | bool

- include_tasks: "install.yml"
  when:
    - not _bind_uninstall
    - bind_enable | bool

- debug:
    msg: Set variable 'bind_enable' to 'yes' if you want.
  when:
    - not (bind_enable | bool)

- include_tasks: "uninstall.yml"
  when:
    - _bind_uninstall
    - not (bind_enable | bool)

- meta: flush_handlers