---
- name: Create molecule platforms
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  become: no

  tasks:
    - name: Start k3s server
      become: yes
      shell: >-
        nohup {{ k3s_cmd }} server > {{ k3s_pid_file }}.log 2>&1 & echo $! > {{ k3s_pid_file }}
