---

# Doing `|from_yaml` when the extension contains nothing yields an empty string ("").
# We need to ensure it's a dictionary or `|combine` (when building `matrix_dimension_configuration`) will fail later.
matrix_dimension_configuration_extension: "{{ matrix_dimension_configuration_extension_yaml|from_yaml if matrix_dimension_configuration_extension_yaml|from_yaml else {} }}"
#
# Pivot variables for readability
#
_matrix_dimension_uninstall: "{{ matrix_dimension_uninstall is defined and matrix_dimension_uninstall | bool }}"
_matrix_dimension_systemd_template: "dimension/systemd-service.j2"
_matrix_dimension_systemd_dest: "/etc/systemd/system/matrix-dimension.service"

_matrix_dimension_config_template: "dimension/configuration.j2"
_matrix_dimension_config_dest: "/etc/systemd/system/matrix-dimension.service"