---
- import_tasks: "checks.yml"
  when:
    - not _taiga_uninstall
    - taiga_enable | bool

- include_tasks: "install.yml"
  when:
    - not _taiga_uninstall
    - taiga_enable | bool

- include_tasks: "uninstall.yml"
  when:
    - _taiga_uninstall
    - not (taiga_enable | bool)

- meta: flush_handlers