---
- name: Install powertop
  apt:
    name: powertop

- name: Render powertop systemd service
  template:
    src: powertop.service.j2
    dest: "{{ powertop_systemd_service_file_path }}"
    backup: no
  notify: Restart powertop service

- name: Enable powertop service
  systemd:
    daemon_reload: yes
    name: powertop
    state: started
    enabled: yes