---
- include: Debian/8/main.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- include: Debian/9/main.yml
  when: ansible_distribution == "Debian" and ansible_lsb.codename == "stretch"