---

- name: Update timezone
  shell: >-
    dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
    enabled: yes

- name: Restart ntp service
  service:
    name: ntp
    state: restarted
    enabled: yes
