# s/qmail
# services
glx_sqmail_inet_bind_info: "0"

glx_sqmail_service_delivery:
  enable: true
  name: "send"
  identifier: "qmail-send"
  script: "run_send"

glx_sqmail_service_smtp:
  enable: false
  name: "smtp"
  identifier: "qmail-smtpd"
  script: "run_smtpd"

glx_sqmail_service_smtps:
  enable: false
  name: "smtps"
  identifier: "qmail-smtpsd"
  script: "run_smtpsd"

glx_sqmail_service_submission:
  enable: false
  name: "submission"
  identifier: "qmail-smtpsub"
  script: "run_smtpsub"

glx_sqmail_service_pop3:
  enable: false
  name: "pop3"
  identifier: "qmail-pop3d"
  script: "run_pop3d"

glx_sqmail_service_pop3s:
  enable: false
  name: "pop3s"
  identifier: "qmail-pop3sd"
  script: "run_pop3sd"

glx_sqmail_service_qmqp:
  enable: false
  name: "qmqp"
  identifier: "qmail-qmqpd"
  script: "run_qmqpd"

glx_sqmail_service_qmtp:
  enable: false
  name: "qmtp"
  identifier: "qmail-qmtpd"
  script: "run_qmtpd"

glx_sqmail_service_qmtps:
  enable: false
  name: "qmtps"
  identifier: "qmail-qmtpsd"
  script: "run_qmtpsd"

glx_sqmail_aviable_services_list:
  - "{{ glx_sqmail_service_delivery }}"
  - "{{ glx_sqmail_service_smtp }}"
  - "{{ glx_sqmail_service_smtps }}"
  - "{{ glx_sqmail_service_submission }}"
  - "{{ glx_sqmail_service_pop3 }}"
  - "{{ glx_sqmail_service_pop3s }}"
  - "{{ glx_sqmail_service_qmqp }}"
  - "{{ glx_sqmail_service_qmtp }}"
  - "{{ glx_sqmail_service_qmtps }}"

# Common and path
glx_slashpackage_dir: "/package"
glx_sqmail_dir: "/var/qmail"
glx_sqmail_ssl_dir: "{{ glx_sqmail_dir }}/ssl"
glx_log_dir: "/var/log"
glx_prefix_dir: "/usr/local"
glx_sqmail_source_dir: "/usr/src"

glx_ucspi_ssl_app_name: "ucspi-ssl"
glx_ucspi_ssl_app_version: "0.11.1"
glx_ucspi_ssl_rsa_key_size: "1024"

glx_sqmail_force_install: True
glx_sqmail_app_name: "sqmail"
glx_sqmail_app_version: "3.3.25"
glx_sqmail_archive_extension: "tgz"
glx_sqmail_archive_filename: "{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}.{{ glx_sqmail_archive_extension }}"
glx_sqmail_archive_path: "{{ glx_sqmail_source_dir }}/{{ glx_sqmail_archive_filename }}"
glx_sqmail_download_repository: "https://gitlab.com/Tuuux/galaxie/raw/master/roles/fehcom-sqmail/files"
glx_sqmail_download_file: "{{ glx_sqmail_download_repository }}/{{ glx_sqmail_archive_filename }}"
glx_sqmail_download_file_sha256sum: "213f7b384ca90c52e04bed154cb244667d849787242740a6cec2629f4f3ed56d"
glx_sqmail_downloaded_file: "{{ glx_sqmail_source_dir }}/{{ glx_sqmail_archive_filename }}"

# Controls
glx_sqmail_domain: "galaxie.ici"
# qmail-send
glx_sqmail_control_me: "{{ ansible_hostname }}.{{ glx_sqmail_domain }}"
glx_sqmail_control_queuelifetime: "604800"
glx_sqmail_control_doublebouncehost: "{{ glx_sqmail_control_me }}"
glx_sqmail_control_doublebounceto: "postmaster"
glx_sqmail_control_bouncemaxbytes: "0"
glx_sqmail_control_concurrencylocal: "10"
glx_sqmail_control_concurrencyremote: "20"
glx_sqmail_control_envnoathost: "{{ glx_sqmail_control_me }}"
glx_sqmail_control_locals:
  - "localhost"
  - "localhost.localdomain"
  - "{{ ansible_hostname }}"
  - "{{ ansible_hostname }}.{{ glx_sqmail_domain }}"
  - "{{ glx_sqmail_domain }}"
glx_sqmail_control_percenthack: ""
glx_sqmail_control_virtualdomains: ""

# qmail-remote
glx_sqmail_control_timeoutconnect: "60"
glx_sqmail_control_timeoutremote: "1200"
# qmail-smtpd
glx_sqmail_control_badhelo:
  - "{{ ansible_default_ipv4.address }}"
  - "{{ ansible_hostname }}.{{ glx_sqmail_domain }}"
  - "localhost"
  - "localhost.localdomain"
glx_sqmail_control_defaultdomain: "{{ glx_sqmail_domain }}"
glx_sqmail_control_plusdomain: "{{ glx_sqmail_domain }}"


glx_sqmail_control_rcpthosts:
  - "{{ glx_sqmail_domain }}"
  - ".{{ glx_sqmail_domain }}"

glx_sqmail_defaultdelivery: "Maildir"
glx_sqmail_control_defaultdelivery: "./{{ glx_sqmail_defaultdelivery }}/"
glx_sqmail_control_concurrencyincoming: "30"
glx_sqmail_control_spfbehavior: "3"
glx_sqmail_control_bouncefrom: "postmaster"
glx_sqmail_control_databytes: "8000000"
glx_sqmail_control_timeoutsmtpd: "30"

glx_sqmail_control_badloadertypes:
  - "Mi5kb"
  - "MzIuZ"
  - "MyLmR"
  - "MyLkR"

glx_sqmail_control_badmailfrom:
  - "# Wildmat evaluates from least specific to most specific"
  - "*"
  - "! "
  - "!*@*.*"
  - "*%*"

glx_sqmail_control_badmimetypes:
  - "TVqQAAMAA"
  - "TVpQAAIAA"
  - "TVpAALQAc"
  - "TVpyAXkAX"
  - "TVrmAU4AA"
  - "TVrhARwAk"
  - "TVoFAQUAA"
  - "TVoAAAQAA"
  - "TVoIARMAA"
  - "TVouARsAA"
  - "TVrQAT8AA"
  - "TVoAAAEAA"

glx_sqmail_control_badrcptto:
  - "# Wildmat evaluates from least specifc to most specific"
  - "*%*"
  - "*\ *@*"
  - "!*@*.*"

glx_sqmail_control_rules_smtpd:
  - '10.0.0.0/8:allow,RELAYCLIENT=""'
  - '172.16.0.0/12:allow,RELAYCLIENT=""'
  - '192.168.0.0/16:allow,RELAYCLIENT=""'
  - '127.0.0.1/31:allow,RELAYCLIENT=""'
  - '::1/127:allow,RELAYCLIENT=""'
  - 'fe80::/10:allow,RELAYCLIENT=""'
  - 'fc00::/7:allow,RELAYCLIENT=""'
  - '=localhost:allow,RELAYCLIENT=""'
  - '=:allow'
  - ':deny'

glx_sqmail_control_rules_qmtpd:
  - '10.0.0.0/8:allow'
  - '172.16.0.0/12:allow'
  - '192.168.0.0/16:allow'
  - '127.0.0.1/31:allow'
  - 'fe80::/10:allow'
  - 'fc00::/7:allow'
  - ':deny'

# users
glx_sqmail_groups:
  nofiles:
    gname: "nofiles"
    gid: "2108"
    description: "sqmail group for auxiliar files"
  sqmail:
    gname: "sqmail"
    gid: "2109"
    description: "sqmail group for binary files"

glx_sqmail_ids:
  alias:
    uname: "alias"
    uid: "7790"
    description: "sqmail Alias user"
    group: "{{ glx_sqmail_groups.nofiles.gname }}"
  qmaild:
    uname: "qmaild"
    uid: "7791"
    description: "sqmail Daemon user"
    group: "{{ glx_sqmail_groups.nofiles.gname }}"
  qmaill:
    uname: "qmaill"
    uid: "7792"
    description: "sqmail Log user"
    group: "{{ glx_sqmail_groups.nofiles.gname }}"
  qmailp:
    uname: "qmailp"
    uid: "7793"
    description: "sqmail Password user"
    group: "{{ glx_sqmail_groups.nofiles.gname }}"
  qmailq:
    uname: "qmailq"
    uid: "7794"
    description: "sqmail Queue user"
    group: "{{ glx_sqmail_groups.sqmail.gname }}"
  qmailr:
    uname: "qmailr"
    uid: "7795"
    description: "sqmail Remote user"
    group: "{{ glx_sqmail_groups.sqmail.gname }}"
  qmails:
    uname: "qmails"
    uid: "7796"
    description: "sqmail Send user"
    group: "{{ glx_sqmail_groups.sqmail.gname }}"
  sqmtls:
    uname: "sqmtls"
    uid: "7797"
    description: "sqmail TLS user"
    group: "{{ glx_sqmail_groups.nofiles.gname }}"

# common setting
glx_sqmail_service_scripts_dir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}/service"
glx_sqmail_conf_thing_dir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}"
glx_sqmail_package_dir: "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_app_name }}-{{ glx_sqmail_app_version }}/package"

# certificate
glx_sqmail_openssl_use_self_signed_cert: true
glx_sqmail_openssl_key_gen: true
glx_sqmail_openssl_dhparam: "1024"
glx_sqmail_openssl_key_bit: "2048"
glx_sqmail_openssl_key_days: "3650"
glx_sqmail_openssl_cert_C: "FR"
glx_sqmail_openssl_cert_ST: "Ile-de-France"
glx_sqmail_openssl_cert_L: "Paris"
glx_sqmail_openssl_cert_O: "Galaxie"
glx_sqmail_openssl_cert_OU: "IT"
glx_sqmail_openssl_cert_CN: "{{ ansible_hostname }}.{{ glx_sqmail_domain }}"
glx_sqmail_openssl_subj: "/C={{ glx_sqmail_openssl_cert_C }}/ST={{ glx_sqmail_openssl_cert_ST }}/L={{ glx_sqmail_openssl_cert_L }}/O={{ glx_sqmail_openssl_cert_O }}/OU={{ glx_sqmail_openssl_cert_OU }}/CN={{ glx_sqmail_openssl_cert_CN }}"


# Alias creation
# http://www.qmail.org/man/man5/dot-qmail.html
glx_sqmail_alias_admins_list:
  - name: "root"
    value:
      - "root@{{ glx_sqmail_domain }}"
  - name: "postmaster"
    value:
      - "root@{{ glx_sqmail_domain }}"
  - name: "mailer-daemon"
    value:
      - "root@{{ glx_sqmail_domain }}"

glx_sqmail_alias_users_list:
  - { name: "anonymous",      value: ["postmaster"] }