---
- name: Create ansible local facts directory
  file:
    path: "{{ item }}"
    mode: 0700
    owner: root
    group: root
    state: directory
  loop:
    - /etc/ansible
    - /etc/ansible/facts.d

- include: hostname.yml
- include: locales.yml
- include: packages.yml
- include: bashrc.yml
- include: vim.yml

- meta: flush_handlers