---
# conf-ld -- loader options to be adjusted (for i386; AMD64 normalydefault)
- name: Check DEB_BUILD_ARCH value
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  register: deb_build_arch
  changed_when: false

- name: "Download https://downloads.plex.tv/plex-media-server/{{ glx_plexmedia_server_version }}/plexmediaserver_{{ glx_plexmedia_server_version }}_{{ deb_build_arch.stdout }}.deb"
  get_url:
    url: "https://downloads.plex.tv/plex-media-server/{{ glx_plexmedia_server_version }}/plexmediaserver_{{ glx_plexmedia_server_version }}_{{ deb_build_arch.stdout }}.deb"
    dest: "{{ glx_plexmedia_server_download_dir }}/plexmediaserver_{{ glx_plexmedia_server_version }}_amd64.deb"
    mode: 0644

- name: "Install {{ glx_plexmedia_server_download_dir }}/plexmediaserver_{{ glx_plexmedia_server_version }}_{{ deb_build_arch.stdout }}.deb"
  apt:
    deb: "{{ glx_plexmedia_server_download_dir }}/plexmediaserver_{{ glx_plexmedia_server_version }}_{{ deb_build_arch.stdout }}.deb"
    state: installed

- name: "Enable the plexmediaserver service"
  service:
    name: "plexmediaserver"
    state: started
    enabled: yes
