---
- name: build ffmpeg | install requirement
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - "autoconf"
    - "automake"
    - "build-essential"
    - "libass-dev"
    - "libfreetype6-dev"
    - "libgpac-dev"
    - "libsdl1.2-dev"
    - "libtheora-dev"
    - "libtool"
    - "libva-dev"
    - "libvdpau-dev"
    - "libvorbis-dev"
    - "libxcb1-dev"
    - "libxcb-shm0-dev"
    - "libxcb-xfixes0-dev"
    - "pkg-config"
    - "texi2html"
    - "zlib1g-dev"
    - "nasm"
    - "cmake"
    - "mercurial"
    - "git-core"
    - "librtmp1"
    - "librtmp-dev"

- name: build ffmpeg | check {{ glx_ffmpeg_source_dir }} directory
  file:
    path="{{ glx_ffmpeg_source_dir }}"
    state=directory

- name: build ffmpeg | clone latest ffmpeg
  git:
    repo=git://source.ffmpeg.org/ffmpeg.git
    dest={{ glx_ffmpeg_source_dir }}/ffmpeg
    accept_hostkey=yes

- name: build ffmpeg | delete "{{ glx_ffmpeg_bin_dir }}/ffmpeg"
  file:
    path="{{ glx_ffmpeg_bin_dir }}/ffmpeg"
    state=absent
  when: glx_ffmpeg_force_install

- name: build ffmpeg | compile ffmpeg
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/ffmpeg"
    creates: "{{ glx_ffmpeg_bin_dir }}/ffmpeg"
  with_items:
    - ./configure --prefix={{ glx_ffmpeg_prefix }} --pkg-config-flags="--static" --extra-cflags=-I{{ glx_ffmpeg_prefix }}/include --extra-ldflags=-L{{ glx_ffmpeg_prefix }}/lib --bindir={{ glx_ffmpeg_bin_dir }} --enable-gpl --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
    - make
    - make install
    - make distclean
