---
# Build yasm
# Download sources yasm
#- name: build ffmpeg | clone yasm
#  git:
#    repo=git://github.com/yasm/yasm.git
#    dest={{ glx_ffmpeg_source_dir }}/yasm
#    accept_hostkey=yes
#
#- name: build ffmpeg | compile yasm
#  command: "{{ item }}"
#  args:
#    chdir: "{{ glx_ffmpeg_source_dir }}/yasm"
#  with_items:
#    - ./autogen.sh
#    - sed -i 's#) ytasm.*#)#' Makefile.in
#    - ./configure --prefix={{ glx_ffmpeg_prefix }}
#    - make
#
#- name: creat yasm package
#  shell: checkinstall \
#          --pkgname="$(grep PACKAGE_NAME config.h | sed -e 's/\#define PACKAGE_NAME "\(.*\)"/\1/g')" \
#          --pkgversion="$(grep PACKAGE_VERSION config.h | sed -e 's/\#define PACKAGE_VERSION "\(.*\)"/\1/g')" \
#          --backup=no \
#          --deldoc=yes \
#          --fstrans=no \
#          --pakdir="{{ glx_ffmpeg_source_dir }}" \
#          --default \
#          make install
#    chdir="{{ glx_ffmpeg_source_dir }}/yasm"

- name: copy files in {{ glx_ffmpeg_source_dir }}/
  copy:
    src="Debian/8/{{ item }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{item  }}"
    backup=no
  with_items:
    - "yasm_1.3.0.orig.tar.gz"
    - "yasm_1.3.0-2.debian.tar.xz"
    - "yasm_1.3.0-2.dsc"

- name: build sox | install requirement
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - "debhelper"
    - "dh-autoreconf"
    - "bison"
    - "gettext"
    - "xmlto"
    - "python"

- name: unarchive {{ glx_ffmpeg_source_dir }}/yasm_1.3.0.orig.tar.gz in {{ glx_ffmpeg_source_dir }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/yasm_1.3.0.orig.tar.gz"
    dest="{{ glx_ffmpeg_source_dir }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: unarchive {{ glx_ffmpeg_source_dir }}/yasm_1.3.0-2.debian.tar.xz in {{ glx_ffmpeg_source_dir }}/yasm-1.3.0
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/yasm_1.3.0-2.debian.tar.xz"
    dest="{{ glx_ffmpeg_source_dir }}/yasm-1.3.0"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: check dpkg --print-architecture
  shell: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: creat yasm package
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/yasm-1.3.0"
    creates: "{{ glx_ffmpeg_source_dir }}/yasm_1.3.0-2_{{ dpkg_arch.stdout }}.deb"
  with_items:
    - dpkg-buildpackage

- name: install yasm
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/yasm_1.3.0-2_{{ dpkg_arch.stdout }}.deb
  changed_when: false