---
- name: copy files in {{ glx_ffmpeg_source_dir }}/
  copy:
    src="Debian/8/{{ item }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{item  }}"
    backup=no
  with_items:
    - "{{ glx_x265_orig_filename }}"
    - "{{ glx_x265_debian_filename }}"
    - "{{ glx_x265_dsc_filename }}"

- name: install requirement
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - "debhelper"
    - "cmake"
    - "libnuma-dev"
    - "python-sphinx"
    - "yasm"

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_x265_orig_filename }} in {{ glx_ffmpeg_source_dir }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_x265_orig_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_x265_debian_filename }} in {{ glx_ffmpeg_source_dir }}/{{ glx_x265_package_name }}_{{ glx_x265_version }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_x265_debian_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{ glx_x265_package_name }}_{{ glx_x265_version }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: check dpkg --print-architecture
  shell: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: creat {{ glx_x265_package_name }} package
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/{{ glx_x265_package_name }}_{{ glx_x265_version }}"
    creates: "{{ glx_ffmpeg_source_dir }}/libx265-79_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb"
  with_items:
    - dpkg-buildpackage -d

- name: install libx265-79_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libx265-79_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install libx265-dev_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libx265-dev_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install x265_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/{{ glx_x265_package_name }}_{{ glx_x265_version }}-{{ glx_x265_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install libx265-doc_{{ glx_x265_version }}-{{ glx_x265_package_version }}_all.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libx265-doc_{{ glx_x265_version }}-{{ glx_x265_package_version }}_all.deb
  changed_when: false