---
- name: copy files in {{ glx_ffmpeg_source_dir }}/
  copy:
    src="Debian/8/{{ item }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{item  }}"
    backup=no
  with_items:
    - "{{ glx_libvpx_orig_filename }}"
    - "{{ glx_libvpx_debian_filename }}"
    - "{{ glx_libvpx_dsc_filename }}"


- name: install requirement
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - "debhelper"
    - "doxygen"
    - "php5-cli"
    - "yasm"

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_orig_filename }} in {{ glx_ffmpeg_source_dir }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_orig_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_debian_filename }} in {{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_package_name }}-{{ glx_libvpx_version }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_debian_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_package_name }}-{{ glx_libvpx_version }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: check dpkg --print-architecture
  shell: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: creat {{ glx_libvpx_package_name }} packages
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/{{ glx_libvpx_package_name }}-{{ glx_libvpx_version }}"
    creates: "{{ glx_ffmpeg_source_dir }}/libvpx3_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb"
  with_items:
    - dpkg-buildpackage

- name: install libvpx3_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libvpx3_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install vpx-tools_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/vpx-tools_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install libvpx-dev_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libvpx-dev_{{ glx_libvpx_version }}-{{ glx_libvpx_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false
