---
- name: copy files in {{ glx_ffmpeg_source_dir }}/
  copy:
    src="Debian/8/{{ item }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{item  }}"
    backup=no
  with_items:
    - "{{ glx_x264_orig_filename }}"
    - "{{ glx_x264_debian_filename }}"
    - "{{ glx_x264_dsc_filename }}"

- name: install requirement
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - "debhelper"
    - "autotools-dev"
    - "dpkg-dev"
    - "libavformat-dev"
    - "libffms2-dev"
    - "libgpac-dev"
    - "yasm"

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_x264_orig_filename }} in {{ glx_ffmpeg_source_dir }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_x264_orig_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: unarchive {{ glx_ffmpeg_source_dir }}/{{ glx_x264_debian_filename }} in {{ glx_ffmpeg_source_dir }}/{{ glx_x264_package_name }}-{{ glx_x264_version }}/
  unarchive:
    src="{{ glx_ffmpeg_source_dir }}/{{ glx_x264_debian_filename }}"
    dest="{{ glx_ffmpeg_source_dir }}/{{ glx_x264_package_name }}-{{ glx_x264_version }}"
    copy=no
    owner="root"
    group="root"
  changed_when: false

- name: check dpkg --print-architecture
  shell: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: creat {{ glx_x264_package_name }} package
  command: "{{ item }}"
  args:
    chdir: "{{ glx_ffmpeg_source_dir }}/{{ glx_x264_package_name }}-{{ glx_x264_version }}"
    creates: "{{ glx_ffmpeg_source_dir }}/libx264-148_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb"
  with_items:
    - dpkg-buildpackage

- name: install libx264-148_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libx264-148_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install libx264-dev_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/libx264-dev_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false

- name: install x264_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb package
  shell: dpkg -i {{ glx_ffmpeg_source_dir }}/{{ glx_x264_package_name }}_{{ glx_x264_version }}-{{ glx_x264_package_version }}_{{ dpkg_arch.stdout }}.deb
  changed_when: false
