---
- name: OpenMeetings | install requirement
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - libreoffice
    - libreoffice-l10n-fr
    - imagemagick
    - libgif4
    - libgif-dev
    - zlib1g-dev
    - liboil0.3
    - unzip
    - make
    - build-essential
    - libfreetype6-dev
    - wget
    - sox
    - flashplugin-nonfree

- name: check DEB_BUILD_ARCH
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  when: ansible_os_family == "Debian"
  register: DEB_BUILD_ARCH
  changed_when: false

- name: download http://old-releases.ubuntu.com/ubuntu/pool/universe/s/swftools/swftools_0.9.0-0ubuntu1_{{ DEB_BUILD_ARCH.stdout }}.deb
  get_url:
    url="http://old-releases.ubuntu.com/ubuntu/pool/universe/s/swftools/swftools_0.9.0-0ubuntu1_{{ DEB_BUILD_ARCH.stdout }}.deb"
    dest="{{ glx_packages_dir }}/swftools_0.9.0-0ubuntu1_{{ DEB_BUILD_ARCH.stdout }}.deb"
  register: swftools_download

#- debug: msg="{{ swftools_download }}"

- name: install swftools_0.9.0-0ubuntu1_{{ DEB_BUILD_ARCH.stdout }}.deb
  apt:
    deb="{{ glx_packages_dir }}/swftools_0.9.0-0ubuntu1_{{ DEB_BUILD_ARCH.stdout }}.deb"
  changed_when: false

- name: block the swftools_0.9.0 version
  shell: echo "swftools hold" | sudo dpkg --set-selections
  changed_when: false
