# the big picture : http://www.fehcom.de/images/sqmail_Big_Picture.pdf

# Stop everything for permit to overwrite fews binarys
- include: services-stop.yml
  tags: install, test

## Intall the requirements
- include: install-cdb.yml
  tags: install-cdb, install

- include: install-sqmail.yml
  tags: install-sqmail, install

## Initital setting
- include: config-controls.yml
  tags: controls, config, install-sqmail, install

- include: config-qmail-send.yml
  tags: controls, config, install-sqmail, install

- include: config-qmail-smtpd.yml
  tags: controls, config, install-sqmail, install

- include: config-qmail-remote.yml
  tags: controls, config, install-sqmail, install

- include: config-qmail-inject.yml
  tags: controls, config, install-sqmail, install

- include: config-alias.yml
  tags: alias, config, install-sqmail, install

- include: config-openssl.yml
  tags: config, install-sqmail, install

- include: install-mta.yml
  tags: config, install-sqmail, install, mta

- include: install-systemd-services.yml
  tags: config, install-sqmail, install, systemd-services

- include: services-enable.yml
  tags: config, install-sqmail, install, systemd-services
