---
k3s_version: v1.19.4+k3s1
k3s_systemd_dir: /lib/systemd/system/
k3s_master_ip: "{{ ansible_default_ipv4.address }}"
k3s_extra_server_args: ""
k3s_extra_node_args: ""
k3s_helm_version: "3.4.1"

k3s_front_certificate_file: "/etc/ssl/private/{{ k3s_public_domain }}.fullchain.crt"
k3s_front_certificate_key_file: "/etc/ssl/private/{{ k3s_public_domain }}.key"
