- name: "Load OS jessie specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.jessie.yml"
        - main.yml

# Installation of tor
- include: install.yml
- include: config.yml
