---

- name: Ensure ntpdate is absent
  apt:
    pkg:
      - ntpdate
    state: absent
    purge: yes

- name: Ensure id ntpd is present
  apt:
    pkg:
      - ntp
    state: present

- name: Ensure tzdata package is installed.
  package:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- name: ntp time source {{ galaxie_ntp_server_ntp_referrals }}
  when: "'internal_machines' in group_names"
  template:
    src: "ntp-server-internal.conf.j2"
    dest: "/etc/ntp.conf"
  notify: restart ntp

- name: ntp time source {{ galaxie_ntp_server_ntp_pool }}
  when: "'external_machines' in group_names"
  template:
    src: ntp-server-external.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- name: remove dhcp-ntp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/dhcp/dhclient-exit-hooks.d/ntp"
    - "/var/lib/ntp/ntp.conf.dhcp"
  notify: restart ntp
