---
- hosts: "{{ scope }}"
  become: true
  gather_facts: yes
  strategy: linear

  tasks:
    - name: Sanity checks
      assert:
        that:
          - amce_domains is defined

    - name: Create acme key directory
      file:
        path: "{{ ssl_certs_dir }}"
        state: directory
        mode: 0710
        owner: root
        group: ssl-cert

    - include_tasks: "{{ playbook_dir }}/inc/_acme-rotate-certificate.yml"
      loop: "{{ amce_domains }}"
      loop_control:
        loop_var: _domain_to_certify
