---
- hosts: "{{ scope }}"
  become: true
  gather_facts: yes
  strategy: linear



  tasks:
    - name: Sanity checks
      assert:
        that:
          - ssl_private_key_directory is defined
          - domains_to_certify is defined

    - name: Create acme key directory
      file:
        path: "{{ ssl_private_key_directory }}"
        state: directory
        mode: 0710
        owner: root
        group: ssl-cert

    - include_tasks: "{{ playbook_dir }}/inc/_acme-rotate-certificate.yml"
      loop: "{{ domains_to_certify }}"
      loop_control:
        loop_var: domain_to_certify

# TODO: freeze or clean bind9