---
- name: Apply a single role
  hosts: "{{ scope }}"
  become: yes
  gather_facts: yes

  tasks:
    - name: Reset bind_dns_keys variable
      set_fact:
        bind_dns_keys: []

    - name: Generate dnssec keys
      include_tasks: "{{ playbook_dir }}/inc/_bind-rotate-managed-user-keys-generate.yml"
      loop: "{{ bind_managed_user_keys }}"
      loop_control:
        loop_var: bind_managed_user_key_specs

    - name: Host vars directory is ready
      file:
        path: "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost
      become: no

    - name: Generate host vars file
      copy:
        dest: "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}/bind_rotate_managed_user_keys.out.yml"
        content: |
          ---
          {{
            {'bind_dns_keys': bind_dns_keys} | to_nice_yaml
          }}
      delegate_to: localhost
      become: no
