---
- hosts: allies
  become: no
  gather_facts: no

- hosts: clans
  become: yes
  gather_facts: no

  tasks:
    - name: "Sanity checks"
      assert:
        that:
          - with_clan is defined

    - name: "Create directory for var files"
      file:
        path: "/etc/ansible/allies"
        state: directory

    - name: "Export vars for ally clan {{ with_clan }}"
      copy:
        dest: "/home/{{ with_clan }}/{{ with_clan }}.vars.yml"
        content: |-
          ---
          {{ clan_alliance_export_content }}

    - name: "Build ssh command to contact"
      set_fact:
        cmd_ssh_to_ally: >-
          ssh {{ hostvars[with_clan].ansible_host }}
          -T
          -l {{ clan_name }}
          -i {{ playbook_dir }}/../keys/{{ clan_name }}/allies/to-{{ with_clan }}

    - debug:
        var: cmd_ssh_to_ally
        verbosity: 1

    - name: "Get vars from ally clan {{ with_clan }}"
      raw: >-
        {{ cmd_ssh_to_ally }}
      register: alliance_query
      delegate_to: localhost
      become: no

    - name: "Persist vars from ally clan {{ with_clan }}"
      copy:
        dest: "{{ playbook_dir }}/../host_vars/{{ with_clan }}.yml"
        content: |-
          {{ alliance_query.stdout }}
      when: alliance_query.rc == 0
      delegate_to: localhost
      become: no
