---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    alliance_key_directory: "{{ playbook_dir }}/../keys/{{ emitter }}/allies"
    alliance_private_key_name: "to-{{ receiver }}"
    alliance_public_key_name: "to-{{ receiver }}.pub"
    alliance_giveaway_public_key_path: "{{ alliance_key_directory }}/{{ alliance_public_key_name }}"

  tasks:
    - name: "Sanity checks"
      assert:
        that:
          - receiver is defined
          - emitter is defined

    - name: "Sanity checks"
      assert:
        that:
          - groups[emitter] is defined
        msg: >-
          Inconsistent inventory: no group '{{ emitter }}' is defined.

    - name: "Sanity checks"
      assert:
        that:
          - receiver in groups[emitter + '_allies']
        msg: >-
          Inconsistent inventory: '{{ receiver }}' is not in the '{{ emitter }}_allies' group.

    - name: Create alliance key directory
      file:
        path: "{{ alliance_key_directory }}"
        state: directory

    - name: "Generate key for {{ emitter }} to contact {{ receiver }}"
      shell: >-
        ssh-keygen -t ed25519
        -N ""
        -q
        -f {{ alliance_key_directory }}/{{ alliance_private_key_name }}
        -C {{ emitter }}@{{ receiver }} <<< y
      args:
        executable: /bin/bash

    - debug:
        msg: |-
          --------  ALLIANCE OFFERING ALMOST COMPLETE --------

          Keys are ready, now share your alliance public key with your the '{{ receiver }}' clan.

          File to give away:
            {{ alliance_giveaway_public_key_path | realpath }}

          When they have the public key file they must execute:

            ansible-playbook playbooks/clan-receive-alliance.yml -e receiver={{ receiver }} -e emitter={{ emitter }} -e clan_public_key_path=${PATH_TO_YOUR_GIVEN_PUB_KEY}

          --------  ALLIANCE OFFERING ALMOST COMPLETE --------