---
- name: Init host for management
  hosts: clans
  gather_facts: no
  tags:
    - system

  pre_tasks:
    - name: "Update package cache (RAW: ALWAYS CHANGED)"
      raw: apt-get update
      tags:
        - raw

    - name: "Install mandatory packages (RAW: ALWAYS CHANGED)"
      raw: >-
        apt-get install -y {{ clan_establish_system_packages | join(' ') }}
      tags:
        - raw

    - name: Safe-upgrade system
      apt:
        update_cache: yes
        upgrade: safe

    - name: Upgrade dist
      apt:
        update_cache: yes
        upgrade: dist

- name: Prepare clan caretaker access
  hosts: clans
  become: no
  gather_facts: no
  tags:
    - caretaker

  tasks:
    - name: Sanity check
      assert:
        that:
          - public_key_file_to_inject is defined
          - clan_caretaker_name is defined
          - clan_caretaker_uid is defined
          - clan_caretaker_gid is defined
          - clan_caretaker_home is defined

    - name: Create caretaker system group
      group:
        name: "{{ clan_caretaker_name }}"
        gid: "{{ clan_caretaker_gid }}"

    - name: Create caretaker system user
      user:
        name: "{{ clan_caretaker_name }}"
        group: "{{ clan_caretaker_name }}"
        home: "{{ clan_caretaker_home }}"
        uid: "{{ clan_caretaker_uid }}"
        shell: /bin/bash

    - name: Add sudo capabilities to caretaker
      copy:
        dest: "/etc/sudoers.d/{{ clan_caretaker_name }}"
        content: |-
          {{ clan_caretaker_name }} ALL=(ALL) NOPASSWD: ALL
        validate: /usr/sbin/visudo -csf %s

    - name: Create dot-ssh directory
      file:
        path: "{{ clan_caretaker_home }}/.ssh"
        state: directory

    - name: Authorize key for caretaker user connections
      lineinfile:
        dest: "{{ clan_caretaker_home }}/.ssh/authorized_keys"
        create: yes
        line: >-
          {{ lookup('file', public_key_file_to_inject) }}

- name: Base server configuration
  hosts: clans
  become: yes
  gather_facts: yes
  tags:
    - base

  roles:
    - common
    - banner
    - ssh
    - ntp
