---
- name: Init host for management
  hosts: clans
  become: yes
  gather_facts: yes
  tags:
    - system

  tasks:
    - name: "Update package cache (RAW: ALWAYS CHANGED)"
      raw: apt-get update
      tags:
        - raw

    - name: "Update package cache (RAW: ALWAYS CHANGED)"
      raw: >-
        apt-get install -y {{ clan_establish_system_packages | join(' ') }}
      tags:
        - raw

    - name: Safe-upgrade system
      apt:
        update_cache: yes
        upgrade: safe

    - name: Upgrade dist
      apt:
        update_cache: yes
        upgrade: dist

    - import_role:
        name: ssh

- name: Prepare clan caretaker access
  hosts: clans
  become: yes
  gather_facts: yes
  tags:
    - caretaker

  tasks:
    - name: Create caretaker system group
      group:
        name: "{{ clan_caretaker_name }}"
        gid: "{{ clan_caretaker_gid }}"

    - name: Create caretaker system user
      user:
        name: "{{ clan_caretaker_name }}"
        group: "{{ clan_caretaker_name }}"
        home: "{{ clan_caretaker_home }}"
        uid: "{{ clan_caretaker_uid }}"
        shell: /bin/bash

    - name: Add sudo capabilities to caretaker
      copy:
        dest: "/etc/sudoers.d/{{ clan_caretaker_name }}"
        content: |-
          {{ clan_caretaker_name }} ALL=(ALL) NOPASSWD: ALL
        validate: /usr/sbin/visudo -csf %s

    - name: Create dot-ssh directory
      file:
        path: "{{ clan_caretaker_home }}/.ssh"
        state: directory

    - name: Authorize key for caretaker user connections
      lineinfile:
        dest: "{{ clan_caretaker_home }}/.ssh/authorized_keys"
        create: yes
        line: >-
          {{ lookup('file', public_key_file_to_inject) }}
      when:
        - public_key_file_to_inject is defined

- name: Prepare clan alliance system
  hosts: clans
  become: yes
  gather_facts: yes
  tags:
    - allies

  tasks:
    - name: Create ansible HQ
      file:
        path: "/etc/ansible/allies"
        state: directory

    - name: Export infos to allies
      copy:
        dest: "/etc/ansible/allies/{{ item }}.vars.yml"
        content: |-
          ---
          {{
            clan_allies_export[item]
            | default(clan_allies_export['all'], true)
            | to_nice_yaml
          }}
      loop: "{{ groups[clan_allies_group] }}"
      tags:
        - refresh

    - import_role:
        name: ssh
