---
- hosts: all
  become: yes

  tasks:
    - name: Update package cache
      raw: apt-get update

    - name: Update package cache
      raw: >-
        apt-get install -y
        python3
        python3-apt
        sudo
        aptitude
        git
        apt-transport-https
        python3-distutils-extra
        python3-setuptools
        python-apt-dev
        libssl-dev
        libffi-dev
        build-essential
        libperl-dev

    - name: Safe-upgrade system
      apt:
        update_cache: yes
        upgrade: safe

    - name: Upgrade dist
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install survival kit
      apt:
        name:
          - vim
          - bash
          - bash-completion
          - sudo

    - name: Create zoe system group
      group:
        name: zoe
        gid: 4200

    - name: Create zoe system user
      user:
        name: zoe
        group: zoe
        home: /home/zoe
        uid: 4200
        shell: /bin/bash

    - name: Add sudo capabilities to zoe
      copy:
        dest: /etc/sudoers.d/zoe
        content: |-
          zoe ALL=(ALL) NOPASSWD: ALL
        validate: /usr/sbin/visudo -csf %s

    - name: Create dot-ssh directory
      file:
        path: /home/zoe/.ssh
        state: directory

    - name: Authorize key for zoe user connections
      lineinfile:
        dest: /home/zoe/.ssh/authorized_keys
        create: yes
        line: >-
          {{ lookup('file', public_key_file_to_inject) }}
      when:
        - public_key_file_to_inject is defined