#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
# configuration variables
    tf_stack: scw
    # tf_workspace: 
# utils variables    
    project_dir: "{{ (playbook_dir + '/..') | realpath }}" 
    tf_stack_dir: "{{ project_dir }}/terraform/{{ tf_stack }}"

    ssh_private_key_file: "{{ project_dir }}/keys/{{ tf_workspace }}.key"
    ssh_public_key_file: "{{ ssh_private_key_file }}.pub"
    
    ready_host_name: "{{ tf_workspace }}"
    raw_host_name: "raw_{{ tf_workspace }}"
    clan_name: "{{ tf_stack }}_{{ tf_workspace }}_clan"
    ready_host_vars_file: "{{ project_dir }}/host_vars/{{ tf_workspace }}.yml"
    raw_host_vars_file: "{{ project_dir }}/host_vars/raw_{{ tf_workspace }}.yml"

  tasks:
    - debug:
        msg: mama
    - name: Sanity checks
      assert:
        that:
          - tf_workspace is defined
          - tf_workspace != 'default'
        msg: "'tf_workspace' must be defined and not 'default'"
    
    - name: Remove clan link from inventory
      lineinfile:
        path: "{{ project_dir }}/hosts"
        state: absent
        line: >-
          {{ clan_name }}

    - name: Remove clan definition from inventory group
      blockinfile:
        path: "{{ project_dir }}/hosts"
        state: absent
        marker: "# {mark} -- playbooks/create_cloud_host.yml -- {{ tf_workspace }}"

    - name: "Destroy workspace {{ tf_workspace }} on {{ tf_stack }}"
      terraform:
        project_path: "{{ tf_stack_dir }}"
        state: absent
        force_init: true
        workspace: "{{ tf_workspace }}"
        variables:
          ssh_public_key_file: "{{ ssh_public_key_file }}"
