---
- hosts: tftp-servers

  vars_files:
    - "galaxie-vars.yml"

  tasks:

    - name: Install tftpd-hpa
      apt:
        pkg: "{{item}}"
        state: present
      with_items:
        - tftpd-hpa

    - name: Remove previus TFTP services version
      apt:
        pkg: "{{item}}"
        state: absent
        purge: yes
      with_items:
        - atftpd
        - tftpd
