---
- hosts: "{{ scope }}"
  become: yes
  gather_facts: no

  vars:
    #gandi_api_key: ~
    #gandi_fqdn: ~
    #gandi_subdomain: ~
    #gandi_sub_ns: ~

    gandi_api_auth_headers:
      Authorization: "Apikey {{ gandi_api_key }}"
    gandi_api_endpoints:
      fqdn_records: >-
        https://api.gandi.net/v5/livedns/domains/{{ gandi_fqdn }}/records
      subdomain_a_record: >-
        https://api.gandi.net/v5/livedns/domains/{{ gandi_fqdn }}/records/{{ gandi_sub_ns }}/A
      subdomain_aaaa_record: >-
        https://api.gandi.net/v5/livedns/domains/{{ gandi_fqdn }}/records/{{ gandi_sub_ns }}/AAAA
      subdomain_ns_record: >- 
        https://api.gandi.net/v5/livedns/domains/{{ gandi_fqdn }}/records/{{ gandi_subdomain }}/NS

  tasks:
    
    - name: Lookup on domain content to validate api key
      uri:
        method: GET
        url: "{{ gandi_api_endpoints.fqdn_records }}"
        headers: "{{ gandi_api_auth_headers }}"
        return_content: yes

    - name: Put A record to scaleway instance
      uri:
        method: PUT
        url: "{{ gandi_api_endpoints.subdomain_a_record }}"
        headers: "{{ gandi_api_auth_headers }}"
        body_format: json
        body:
          rrset_values:
            - "{{ public_ipv4 }}"
          rrset_ttl: 300
        return_content: yes
        status_code: 201

    - name: Put AAAA record to scaleway instance
      uri:
        method: PUT
        url: "{{ gandi_api_endpoints.subdomain_aaaa_record }}"
        headers: "{{ gandi_api_auth_headers }}"
        body_format: json
        body:
          rrset_values:
            - "{{ public_ipv6 }}"
          rrset_ttl: 300
        return_content: yes
        status_code: 201

    - name: Put NS record to scaleway instance
      uri:
        method: PUT
        url: "{{ gandi_api_endpoints.subdomain_ns_record }}"
        headers: "{{ gandi_api_auth_headers }}"
        body_format: json
        body:
          rrset_values:
            - "{{ gandi_sub_ns }}"
          rrset_ttl: 300
        return_content: yes
        status_code: 201
