---
- hosts: clans
  become: yes
  gather_facts: yes

  vars:
    jitsi_meet_server_name: "meet.clans.galaxie.family"

  pre_tasks:

    - name: Install jitsi project apt repository
      apt_repository:
        repo: "deb http://ftp.us.debian.org/debian sid main"
        state: "present"
        filename: adoptopenjdk
        update_cache: yes

    - apt:
        name:
          - default-jre-headless
        state: absent

    - apt:
        name:
          - openjdk-8-jre-headless
        state: present

    - apt:
        name:
          - openjdk-11-jre-headless
        state: absent

  roles:
    - role: jitsi-meet
      vars:
        jitsi_meet_ssl_cert_path: "/etc/ssl/private/meet.clans.galaxie.family.fullchain.crt"
        jitsi_meet_ssl_key_path: "/etc/ssl/private/meet.clans.galaxie.family.key"
        jitsi_meet_configure_nginx: true

  post_tasks:
    # https://github.com/jitsi/jicofo/blob/master/README.md#certificates
    - name: Copy root certificate from prosody
      become: true
      copy:
        remote_src: yes
        src: "/var/lib/prosody/{{ jitsi_meet_server_name }}.crt"
        dest: "/usr/local/share/ca-certificates/"

    - name: Run update-ca-certificates for Jicofo
      become: true
      command: update-ca-certificates