---
- hosts: "{{ scope }}"
  become: yes
  gather_facts: no

  vars_prompt:
    - name: account_password
      prompt: "What is your password?"

    - name: account_password_confirmation
      prompt: "What is your password (confirmation)?"

  tasks:
    - name: Sanity checks
      assert:
        that:
          - account is defined

    - name: Sanity checks
      assert:
        that:
          - "{{ account_password == account_password_confirmation }}"

    - name: Force email account password in dovecot
      lineinfile:
        regex: >-
          ^{{ account }}.*
        line: >-
          {{ account }}:{CRYPT}{{ account_password | password_hash('bcrypt') }}:::
        dest: /etc/dovecot/users