---
- hosts: "{{ scope }}"
  become: yes
  gather_facts: no

  tasks:
    - name: Sanity checks
      assert:
        that:
          - account is defined
          - password is defined

    - name: Force email account password in dovecot
        regex: >-
          ^{{ account }}.*
        line: >-
          {{ account }}:{CRYPT}{{ password | password_hash('bcrypt') }}:::
        dest: /etc/dovecot/users