---
- name: Gathering facts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - always

- name: Apply critical services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - critical
    - black

  roles:
    - role: "system_base"
    - role: "ssh"
    - role: "ntp"
    - role: "firewall"

- name: Apply core services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - core
    - cyan

  roles:
    - role: "bind"
    - role: "metrics"
    - role: "mailserver"
