---
- name: Gathering facts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - always

- name: Apply critical services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - critical

  roles:
    - role: "common"
    - role: "banner"
    - role: "ssh"
    - role: "ntp"
#    - role: "ufw"

- name: Apply core services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - core

  roles:
    - role: "bind"
    - role: "metrics"
    - role: "mailserver"
