---
- name: Gathering facts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - always

- name: Apply critical services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - critical
    - black
  roles:
    - role: "system_base"
    - role: "system_users"
    - role: "backup"
    - role: "monitor"
    - role: "firewall"
    - role: "dns"
    - role: "mailserver"
