---
- name: Gathering facts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - always

- name: Deploy system-level services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: yes
  roles:
    - role: "system_base"
    - role: "system_users"
    - role: "firewall"
    - role: "dns"
    - role: "mailserver"
    - role: "container"
    - role: "monitor"
