---
- name: Gather facts about all hosts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - gather

- name: Apply core services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: yes

  roles:
    - role: "common"
    - role: "banner"
    - role: "ssh"
    - role: "ntp"
#    - role: "firewall"
    - role: "bind"
    - role: "metrics"

- name: Apply core services - mailserver
  hosts: "{{ scope }}"
  become: yes
  gather_facts: yes
  # mitogen does not support loading python dns module
  strategy: linear

  roles:
    - "mailserver"