---
- name: Gathering facts
  hosts: "clans:!allies"
  become: yes
  gather_facts: yes
  tags:
    - always

- name: Apply critical services
  hosts: "{{ scope }}"
  become: yes
  gather_facts: no
  tags:
    - hlh
    - grey
  roles:
    - role: "rproxy"
      vars:
        nginx_skip_enabling_sites: yes
    - role: "container"