---
- hosts: "{{ scope }}"
  become: yes
  strategy: linear

  vars:
    time_machine_current_backup_dir: "{{ time_machine_backup_dir }}/{{ restore }}"

  tasks:
    - name: Sanity check
      assert:
        that:
          - restore is defined
          - restore | length > 0
        msg: >-
          Defined 'restore' var to target a backup directory to restore.

    - name: Find existing backups
      import_tasks: "{{ playbook_dir }}/inc/_time_machine_find_backups.yml"

    - name: Load profile
      include_vars: "{{ time_machine_current_backup_dir }}/restore_profile.yml"

    - name: "Restore {{ scope }} -- {{ backup }}"
      synchronize:
        mode: push
        src: "{{ time_machine_current_backup_dir }}/{{ item[0].key }}/{{ item[1].name }}/"
        dest: "{{ item[1].path }}"
        use_ssh_args: yes
        compress: yes
        archive: yes
        rsync_opts: "{{ time_machine_rsync_opts_push }}"
      loop: "{{ restore_profile | dict2items | subelements('value.locations') }}"
