---
- import_tasks: "checks.yml"
  when:
    - not _bind_uninstall
    - bind_enable | bool

- include_tasks: "install.yml"
  when:
    - not _bind_uninstall
    - bind_enable | bool

- include_tasks: "uninstall.yml"
  when:
    - _bind_uninstall
    - not (bind_enable | bool)

- meta: flush_handlers