---
- name: delete previous {{ glx_ndjbdns_source_dir }} source directory
  file:
    path: "{{ glx_ndjbdns_source_dir }}"
    state: absent
  when: glx_ndjbdns_force_install

- name: check {{ glx_ndjbdns_source_dir }} directory
  file:
    path: "{{ glx_ndjbdns_source_dir }}"
    state: directory

- name: install required software
  apt:
    pkg:
      - git
      - build-essential
      - automake
      - pkg-config
      - rsyslog
    state: present

- name: get n-djbdns sources from {{ glx_ndjbdns_git_repo }} git repository
  git:
    repo: "{{ glx_ndjbdns_git_repo }}"
    dest: "{{ glx_ndjbdns_source_dir }}"
    update: yes

- name: ensure {{ glx_ndjbdns_source_dir }}/README file exists
  copy:
    content: ""
    dest: "{{ glx_ndjbdns_source_dir }}/README"
    force: no
    group: root
    owner: root
    mode: 0555

- name: fixe https://github.com/pjps/ndjbdns/issues/14
  shell: aclocal && autoconf && automake --add-missing
    chdir="{{ glx_ndjbdns_source_dir }}"
  changed_when: false

- name: ./configure --prefix={{ glx_prefix_dir }} --sysconfdir={{ glx_sysprefix_dir }}
  shell: ./configure --prefix={{ glx_prefix_dir }} --sysconfdir={{ glx_sysprefix_dir }}
  args:
    chdir: "{{ glx_ndjbdns_source_dir }}"
  changed_when: false

- name: make
  shell: make
  args:
    chdir: "{{ glx_ndjbdns_source_dir }}"
  changed_when: false

- name: make install
  shell: make install
  args:
    chdir: "{{ glx_ndjbdns_source_dir }}"
  changed_when: false

- name: copy services
  shell: cp {{ item }} /lib/systemd/system/
  args:
    chdir: "{{ glx_ndjbdns_source_dir }}/etc/systemd"
  with_items:
    - "axfrdns@.service"
    - "axfrdns.socket"
    - "dnscache.service"
    - "rbldns.service"
    - "walldns.service"
  changed_when: false

- name: check /etc/rsyslog.d/20-ndjbdns.conf
  template:
    src: etc/rsyslog.d/20-ndjbdns.conf.j2
    dest: "/etc/rsyslog.d/20-ndjbdns.conf"
    backup: no
  notify:
    - restart rsyslog

- name: copy ndjbdns.logrotate to /etc/logrotate.d/ndjbdns
  shell: cp ndjbdns.logrotate /etc/logrotate.d/ndjbdns
  args:
    chdir: "{{ glx_ndjbdns_source_dir }}"
  changed_when: false

- name: Clean installation
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/local/lib/systemd/system/axfrdns@.service"
    - "/usr/local/lib/systemd/system/axfrdns.socket"
    - "/usr/local/lib/systemd/system/dnscache.service"
    - "/usr/local/lib/systemd/system/rbldns.service"
    - "/usr/local/lib/systemd/system/tinydns.service"
    - "/usr/local/lib/systemd/system/walldns.service"
  changed_when: false

- name: regen unit files
  shell: systemctl daemon-reload